### ISSUE TITLE
False promise ending after the round has been completed can kill the player.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#109]
Not certain but I believe what happened is false promised ended during the brief moment between my team finishing the round and us being teleported to the fountain. This caused my team mate to die in that brief period (he had taken enough damage while in false promise to die when it ended). This caused him to lose an aegis and when he respawned he did not get teleported to the fountain.

**Comment by Draze22** [comment]
Seems like false promise is automatically ending when you kill the final creep of the round instead of at the end of its duration. This is causing players to die (if they took enough damage during false promise) instead of getting teleported to the fountain. This results in the player losing an aegis and staying in their arena until the next round. This bug is far less niche than I originally thought.

**Comment by Draze22** [comment]
This happened after a duel where the the death prophet had false promise on her and died in the fountain from it ending but didn't respawn because she had no aegis' left.
![image](https://user-images.githubusercontent.com/63279022/80273473-a5909380-8715-11ea-9aa5-a705965de736.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81497486-264cb380-9302-11ea-9ea1-cab7cbe9edce.png)

**Comment by Draze22** [comment]
I believe this would be fixed if #203 were to get fixed and am therefor closing this issue.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87843167-85780700-c8f5-11ea-8783-69445e117b58.png)
![image](https://user-images.githubusercontent.com/63279022/87843171-99bc0400-c8f5-11ea-88ed-6fc70c4ee7fb.png)
![image](https://user-images.githubusercontent.com/63279022/87843168-932d8c80-c8f5-11ea-9b1a-ed4b6244e2a2.png)

**Comment by SanctusAnimus** [comment]
Should be fixed
