### ISSUE TITLE
Two heroes on the same team in duos both having marksmanship is buggy.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#133]
There are no problems when both the heroes are melee.
When one of the heroes is melee and the other is ranged the ranged heroes agility rapidly switches between receiving the marksmanship aura from them self and their team mate while they are moving.
I have no clue what happens when both heroes are ranged.

**Comment by SanctusAnimus** [comment]
Probably related to both auras utilizing one non-stackable modifier. Not really fixable for now, marking as delayed, i think
