### ISSUE TITLE
Rearm during snowball and omnislash allows as-much-as-your-mana-can-handle snowball/omnislash

### ISSUE THREAD

**Issue by mmdts** [dota2unofficial/custom_hero_clash_issues#145]
Or permanent omnislash if you've got essence flux/aura

I've omnislashed duels and waves from start to end on jugg with it.

**Comment by darklordabc** [comment]
Is this a bug? Sounds like something you should be able to do?

**Comment by SanctusAnimus** [comment]
technically yes

**Comment by mmdts** [comment]
It's more uncounterable in duels than shadow realm + rearm (which is only stoppable by properly timing AoE stuns).

If rearm golems and rearm chrono deserve a fix, then this does too.
