### ISSUE TITLE
Give players the option to view the end game screen once someone wins.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#151]
Currently if the last player alive continues fighting creeps anyone spectating that wants to see the end game screen has to wait for them to lose to see it. 

What I'm suggesting is that when this final player gets the option to continue playing everyone spectating gets the option to leave and view the end game screen or continue watching.

**Comment by Draze22** [comment]
The wouldn't be as necessary if the mmr change shown when a player loses was 100% accurate.

**Comment by Sheodar** [comment]
It's not a problem, because now  mmr changes absoluetly true. + We will create new full endgame screen
