### ISSUE TITLE
Crash screenshots/details megathread.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#172]
Put all crash screenshots/details here that don't identify the cause of the crash so they don't clutter the rest of the GutHub but are all easily accessible for comparison.

If and when patterns start to arise and the causes become more clear we can make new entries for the specific causes.

┆Issue is synchronized with this [Trello card](https://trello.com/c/8TjqLGKw) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
No details provided.
![image](https://user-images.githubusercontent.com/63279022/81291694-9dd5d500-90ad-11ea-9f2a-13896890d373.png)

**Comment by Draze22** [comment]
Just had a crash upon entering a round (saytres iirc) round 80. (Australia Is My City)

No screenshot provided.

**Comment by Draze22** [comment]
Also a silencer just got familiars and spawned them and crashed everyone out of the game. - Elusive346

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81475972-a7e50880-9252-11ea-801e-562a4de15476.png)

No screenshot provided.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81491255-bc1b1b00-92cf-11ea-8e40-5e4bad6a8618.png)

This needs confirmation as I'm pretty sure I've done this and had nothing unusual happen.

**Comment by Draze22** [comment]
I was just in a game when the server crashed with no obvious cause. The last thing that happened in my creep arena before the crash was my team mate multicast wild axes while also casting (maybe multicasting) death ward (he cast wild axes, then cast death ward and both multicast meaning the second/third cast of wild axes happened after the first cast of death ward).

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82200706-b31af100-9942-11ea-8c33-c53d3154de2b.png)
![image](https://user-images.githubusercontent.com/63279022/82200679-ab5b4c80-9942-11ea-9e19-5160e803b970.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82746221-b8f45480-9dd0-11ea-8a0b-593008df73eb.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83319083-88079a00-a27e-11ea-986e-643131ccf9eb.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83552449-22046680-a54d-11ea-8199-beda4676d508.png)
![image](https://user-images.githubusercontent.com/63279022/83552463-2af53800-a54d-11ea-8b5f-e90833e9d174.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83553088-15344280-a54e-11ea-9a69-b4427ad451ba.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84591600-2bfa6380-ae83-11ea-9f98-e5726de8f2e0.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85420919-2acde280-b5b7-11ea-9243-043786d7ab47.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85536429-6ff52180-b656-11ea-80ff-e68d04d5f6b3.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85637594-f9dcd300-b6c6-11ea-80f1-425205e42950.png)
![image](https://user-images.githubusercontent.com/63279022/85637607-ffd2b400-b6c6-11ea-9a9b-05f22357112a.png)
![image](https://user-images.githubusercontent.com/63279022/85637620-082aef00-b6c7-11ea-9b9c-f61cf4ee7374.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/86504369-d3234880-bdfa-11ea-942c-155e20a2f057.png)
![image](https://user-images.githubusercontent.com/63279022/86504374-dd454700-bdfa-11ea-9490-a302eb068db5.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/88886398-b9501680-d27d-11ea-9d5d-da01b08c33bc.png)

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104383411-e9694880-5583-11eb-887f-5a9ed282b11e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104713863-90163a80-5778-11eb-8c7e-e2131e061626.png)
![image](https://user-images.githubusercontent.com/63279022/104713872-93a9c180-5778-11eb-8519-1314debabf3f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104784386-45c6a500-57dc-11eb-8bd6-7d2c1942dbb1.png)
![image](https://user-images.githubusercontent.com/63279022/104784393-4828ff00-57dc-11eb-95a7-aa7e966eb099.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104827468-108c8680-58b2-11eb-9500-14a3b923d6d5.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/104859833-08991900-597c-11eb-822d-067c7aea8db0.png)
![image](https://user-images.githubusercontent.com/63279022/104859840-0df66380-597c-11eb-8fdd-384656c6d582.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/105138098-84e05780-5b48-11eb-8f2c-cba719b6834d.png)
![image](https://user-images.githubusercontent.com/63279022/105138105-87db4800-5b48-11eb-8de0-727276f738e3.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/105437155-a0687100-5cb4-11eb-9a8c-a4b453ab2179.png)

**Comment by Draze22** [comment]
https://clips.twitch.tv/ObservantHomelyKimchiFeelsBadMan

Host had turned on damage casts spells mode which could be relevant.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/105652050-8628d000-5f0c-11eb-96f3-4366cc49144f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106101932-bda8ae00-6192-11eb-8d7f-e92ac1cbbd6d.png)
![image](https://user-images.githubusercontent.com/63279022/106101937-c0a39e80-6192-11eb-97a4-309633b113fd.png)

**Comment by Draze22** [comment]
Player learned, skilled and used mass serpent ward during a duos duel and the server crashed at the end of the cast point. He did not have multicast.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/107208124-435f1000-6a55-11eb-94e1-f57427aeb5a3.png)

**Comment by Snoresville** [comment]
I feel like some of these issues are "intentional"

**Comment by Draze22** [comment]
This hasn't been very useful so I'm closing it for now.
