### ISSUE TITLE
If a team/player goes out mid duel and it starts sudden death, losing that duel will lose an aegis/gain a curse

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#18]

**Comment by darklordabc** [comment]
Goes out? Over what point?
This issue confuses me could you explain it again please

**Comment by AustraliaIsMyCity** [comment]
If during a duel another player goes out which pushes the game to the point where losing a duel causes players to lose an aegis the player who loses the duel will still lose an aegis

**Comment by darklordabc** [comment]
What does goes out mean?

**Comment by AustraliaIsMyCity** [comment]
if theyre eliminated by dying to creeps without an aegis available

**Comment by Draze22** [comment]
Once a certain number of teams (3) or a certain number of players (4 or 5, don't remember which) are remaining you lose an aegis every time you lose a duel. The issue stated here is that you can start a duel with 4 teams remaining, a team not in the duel dies and the team that loses the duel loses an aegis despite thinking they won't when they start the duel.

**Comment by darklordabc** [comment]
So the chance of losing an aegis in a duel should be determined only at the start of the duel, it shouldn't change because another player (who isn't in the duel) gets eliminated from the game.

**Comment by Draze22** [comment]
Yes

**Comment by Draze22** [comment]
This happened again to me.
