### ISSUE TITLE
Reconnecting and not being able to control hero.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#184]
![image](https://user-images.githubusercontent.com/63279022/81490815-f681b980-92c9-11ea-941e-ef7fedd231eb.png)

There have been a few people experiencing this.

**Comment by Draze22** [comment]
Another person complaining about this and they gave me some more info about the bug. Seems like its caused by disconnecting during the hero picking phase and reconnecting after it. Not sure exactly how long after the hero picking phase it has to be (might have to be after the first round has started or ended) for this bug to occur. Once they've reconnected they can't control their hero, pick innates, pick abilities or place bets. Also all the screenshots have io as the hero 'selected'. 

![image](https://user-images.githubusercontent.com/63279022/81570215-a0089e00-93e3-11ea-9199-d903d1f3134c.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82117499-acaa3f00-97b3-11ea-8557-6773e62310ae.png)

**Comment by Sheodar** [comment]
If it's still problem - reopen this issue (we already fixed some errors for this)
