### ISSUE TITLE
Add a toggled button for single player that gives infinite preparation time.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#187]
![image](https://user-images.githubusercontent.com/63279022/81491151-e10e8e80-92cd-11ea-8b44-97e6931dd950.png)

**Comment by darklordabc** [comment]
Is there a balance concern here? If you have unlimited preparation time, you have unlimited time to wait for cooldowns to come off, allowing you to use all your spells, every round? Is that a problem?

**Comment by AustraliaIsMyCity** [comment]
This was added in the form of the infinite pause button (if we just had a timer extension that went on forever then players could abuse the various GPM items plus it would massively throw off the balance by allowing cooldowns to reduce)

**Comment by fcalife** [comment]
I want to add that pauses cannot be infinite in dedicated servers. The game automatically unpauses after 5 (10?) minutes, and you are still subject to the 3 pause limit.
