### ISSUE TITLE
Dying shortly after killing a creep round makes you not respawn.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#203]
This results in the player either losing an aegis if they have one which is not really a problem or they lose if they don't have any left, unless its duos and in that case the are dead for a round and revived if their team mate wins the creep round.

![image](https://user-images.githubusercontent.com/63279022/81642158-1ea61f80-9466-11ea-904f-245641487996.png)

Something different happens when you get put in a duel after dying like this and is detailed in issue #51 .

**Comment by Draze22** [comment]
Can probably fix this by making the player invulnerable instantly once the final creep of the creep round dies. I believe doing this would also fix the buggy mess that is false promise ending after the round has finished.

**Comment by Draze22** [comment]
This bug causes you to respawn in the creep arena if you have reincarnation.

![image](https://user-images.githubusercontent.com/63279022/81644055-5ca54280-946a-11ea-9aaf-e13a1355d2a1.png)

**Comment by mmdts** [comment]
Partly related to #51

**Comment by Draze22** [comment]
This seems like a very similar bug if not the same bug with slightly altered circumstances.

![image](https://user-images.githubusercontent.com/63279022/82029426-561d0200-96da-11ea-956e-7c563bb6166f.png)
![image](https://user-images.githubusercontent.com/63279022/82029460-61702d80-96da-11ea-9656-4a202cd7812f.png)

**Comment by SanctusAnimus** [comment]
Should be fixed, reopen if reoccures
