### ISSUE TITLE
Neutral creep abilities aren't affected by status resistance.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#204]
Fixing this would require a lot of work (I believe the abilities have to be redesigned in order to have them affected by status resistance) but would likely be greatly appreciated by the player base.

**Comment by AustraliaIsMyCity** [comment]
I'll work on this

**Comment by AustraliaIsMyCity** [comment]
afaik this is now done, lmk if I missed any abilities
