### ISSUE TITLE
Duel betting unavailable

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#205]
For situations where no one could bet on the current duel.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81786114-9b0e3080-9542-11ea-9462-c4e8aec0606d.png)
![image](https://user-images.githubusercontent.com/63279022/81786142-a3ff0200-9542-11ea-9120-9203d628c7a6.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81786346-d9a3eb00-9542-11ea-9163-30b4ed95f380.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/81787961-1ffa4980-9545-11ea-9fd4-474e109caed2.png)

**Comment by Draze22** [comment]
https://github.com/darklordabc/chc2issues/issues/193#issue-615365103

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82009286-44276900-96b2-11ea-8cc2-2b813606b827.png)

**Comment by Draze22** [comment]
This example is especially weird.

![image](https://user-images.githubusercontent.com/63279022/82009309-543f4880-96b2-11ea-8880-45b59a13102e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82138510-66f97f00-9864-11ea-8229-0a1eacb551c6.png)
![image](https://user-images.githubusercontent.com/63279022/82138520-74af0480-9864-11ea-9d41-9533c85d935f.png)
![image](https://user-images.githubusercontent.com/63279022/82138524-7e386c80-9864-11ea-80b7-7832237cf7ce.png)
![image](https://user-images.githubusercontent.com/63279022/82138528-87293e00-9864-11ea-8549-d5e6b5d66513.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82729296-c6123480-9d39-11ea-9d5a-1446bba48598.png)

This may finally explain this bug.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/83428230-5ad10c80-a475-11ea-8607-0d0608bbedee.png)

**Comment by Draze22** [comment]
Possible explanation.

![image](https://user-images.githubusercontent.com/63279022/84092839-e8939580-aa3b-11ea-909f-19c53581bed8.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84597451-74c41380-aea7-11ea-8934-1eadf3afb3db.png)
![image](https://user-images.githubusercontent.com/63279022/84597467-886f7a00-aea7-11ea-920f-1de07baf4d35.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84603273-76560180-aed0-11ea-8a69-9c143bdeb308.png)

**Comment by Draze22** [comment]
This seems like the old Abaddon duel UI bug but with the new duel UI.

![image](https://user-images.githubusercontent.com/63279022/86087912-a57f8c00-bae8-11ea-9490-74c58b93d379.png)
![image](https://user-images.githubusercontent.com/63279022/86087940-af08f400-bae8-11ea-89c3-fad9afb5b204.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/86512491-1e167d80-be46-11ea-90e3-8163e88c69bf.png)
![image](https://user-images.githubusercontent.com/63279022/86512495-24a4f500-be46-11ea-9b84-905d44d64c74.png)

**Comment by Draze22** [comment]
Specifically happened with the Templar assassin.
![image](https://user-images.githubusercontent.com/63279022/87217166-ebaada00-c389-11ea-964d-10646855715f.png)
![image](https://user-images.githubusercontent.com/63279022/87217204-1e54d280-c38a-11ea-96ff-a31344268bf8.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87383016-bc8ba700-c5db-11ea-824c-ba890f5ff2ef.png)
![image](https://user-images.githubusercontent.com/63279022/87383032-c4e3e200-c5db-11ea-9d24-1452f81f44da.png)

**Comment by SanctusAnimus** [comment]
Is this bug still happens?

**Comment by Draze22** [comment]
Don't think so, closing for now.
