### ISSUE TITLE
Nerf crown of the dominator in duels.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#219]
Crown of the dominator currently makes summon builds insanely strong in duels. The bonus given to summons needs to be decreased just like how spell amp from intelligence is decreased in duels. Somewhere between 33% and 50% effectiveness in duels is what i would recommend.

Not sure how easy this is to implement but it is a huge balance issue with the game.

**Comment by darklordabc** [comment]
I think this is no longer an issues because we have reworked summons, and they are nerfed in duels. @Draze22 can you close this if I'm correct.

**Comment by Draze22** [comment]
Yes, this is no longer an issue.
