### ISSUE TITLE
Death scoreboard shows an inaccurate change in mmr.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#223]
The notification/scoreboard that shows your placement and mmr change when you die is highly inaccurate as it seems to be using a vastly different formula to the actual mmr formula.

**Comment by SanctusAnimus** [comment]
Is it still an issue? IIRC we fixed that a long time ago, reopen if i'm wrong

**Comment by Draze22** [comment]
It's more accurate than it was but often still inaccurate.
