### ISSUE TITLE
The 200 second timer doesn't kill some players

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#226]
Not sure exactly how the 200 second timer ending is supposed to work but it seems to kill a random player for some reason.

![image](https://user-images.githubusercontent.com/63279022/82723012-d365f980-9d0e-11ea-810a-7216c5c43da8.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/82723054-35266380-9d0f-11ea-815b-6732c964537e.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84886505-dd91d280-b0d7-11ea-9554-caedebdfe66b.png)
![image](https://user-images.githubusercontent.com/63279022/84886475-d4086a80-b0d7-11ea-9e52-86a53597c264.png)

**Comment by Draze22** [comment]
In the latest update it seems to do nothing, not even end the round.

**Comment by fcalife** [comment]
this was supposed to be fixed, can we set up a time to test it live?

**Comment by Draze22** [comment]
I can do a quick test of it now

**Comment by Draze22** [comment]
This should mostly be fixed now, there are only a handful of skills that stop overtime ending from killing you.

**Comment by Draze22** [comment]
Still getting reports of this.

![image](https://user-images.githubusercontent.com/63279022/89866836-90237480-dbf3-11ea-98ed-8ac5b6d31b00.png)

**Comment by Draze22** [comment]
Haven't gotten any reports of this for a long time.
