### ISSUE TITLE
Spell amp sometimes doesn't display accurately.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#241]
I haven't been able to figure out exactly why spell amp from intelligence doesn't display properly sometimes but I know when it does happen it doesn't display while in the fountain, the creep arena and possibly the duel arena too. In duos it often happens where you can't see your own spell amp but your partner can see how much spell amp you have. Seems to fix itself at random and I've seen no evidence that this is anything other than a visual bug.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85212924-12817c00-b39b-11ea-80ff-a719f4c7051d.png)
This states that all spell amp is affected by the bug (which seems likely) and that the bug isn't just visual (which seems unlikely due to the visual bug only occur to a player checking their own intelligence).

**Comment by Draze22** [comment]
This seems related to issue #35 and while watching a Dota 2 tournament one of the casters noticed that a player's assault cuirass did not seem to be appearing to providing them with the 10 base armour it usually provides. This suggests that this bug can relate to both armour and spell amp from items and talents (at the very least) and is a bug in all of Dota 2 and not just CHClash.

**Comment by fcalife** [comment]
This is the same issue that causes some talents to not display their values sometimes. People usually report it as "+x damage talent didn't work gg shit game fuck you"

**Comment by Draze22** [comment]
That's issue #35 but good to know you noticed the connection too.
