### ISSUE TITLE
Punishment/compensation when a player abandons in duos.

### ISSUE THREAD

**Issue by Wintarogar** [dota2unofficial/custom_hero_clash_issues#244]
Players in a duet simply leave the game, spoiling the rating and all the pleasure of the game. A heavy fine is required, increasing from the ban for an hour to a week
Either the rating should not be considered if the partner left the game before the 30th wave. Or compensation for leaving the game in the form of buffs or books

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/84089312-efb5a600-aa31-11ea-9733-089fdc19147e.png)

**Comment by Draze22** [comment]
Duplicate issue.
