### ISSUE TITLE
Compensation Needed

### ISSUE THREAD

**Issue by Wintarogar** [dota2unofficial/custom_hero_clash_issues#261]
The next time you leave the game with a teammate in a duet, you need compensation of the type + 50% damage to creeps, + 50% gold or goldbook every 5 rounds or the same, the ability to exchange skills with an unreliable noob who completely left the game

**Comment by Draze22** [comment]
Personally I think allowing the now solo player to swap abilities with their partner freely, getting all their gold, being able to sell their items (for more gold) would be the first place to start to solve this issue. 

Giving bonus damage (+50% as suggested) against creeps would need to be carefully considered as it could incentivize duos teams to draft and play such that one team member is very strong and have the weaker team member leave to gain an overall advantage.
