### ISSUE TITLE
Starforce + spell amp rework proposal

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#263]
For discussion.

---

### Current spell amp:

+0.6% per int during rounds
+0.2% per int during duels

### Current Sky Staff:

+41 int
+20% mana cost/manaloss reduction
+25% spell amp

### Current Starforce:

+82 int (+16.4% spell amp in duels, +49.2% spell amp in rounds)
+35% mana cost/manaloss reduction
+50% spell amp

------

### Proposed spell amp:

+0.6% per int during rounds
+0.2% per int during duels

Does not affect percentage-based spells: Firestorm, Earth Splitter, Arctic Burn, Infernal Blade, Midnight Pulse, Static Field, Reaper's Scythe, Heartstopper Aura, Life Break, Sun Ray. These abilities are reverted to their normal values (or close to that).

### Proposed Sky Staff:

same recipe and cost as today

+41 int
+15% mana cost/manaloss reduction
+20% spell amp

**Arcane Might** - grants an additional 0.6% spell amp per int during rounds. Does not stack with itself or Star Force's passive.

### Proposed Starforce:

Sky Staff + Dagon 5 (13,050 gold)

+80 int
+10 strength
+10 agility
+20% mana cost/manaloss reduction
+30% spell amp

**Arcane Supremacy** - grants an additional 1.4% spell amp per int during rounds. Does not stack with itself or Sky Staff's passive.

**The Boomstick** (active, unit target, 15s CD, 200 mana cost, 800 cast range) - a ray of raw magic energy bounces through the target and nearby enemies, dealing 800 magic damage to each. 600 bounce radius.

---

Some numbers to better situate the before vs after:

![image](https://user-images.githubusercontent.com/7921728/84585076-31ec3800-ade2-11ea-9f55-23eb9941263a.png)

**Comment by Draze22** [comment]
I think the spell amp during rounds might be a little too high but I like the design of the item. 

As a side note how many times does The Boomstick bounce?

**Comment by Draze22** [comment]
This was implemented.
