### ISSUE TITLE
Rework Torn Page of Retraining

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#264]
For discussion.

---

### Current:

1000 gold
Active: unlearns a random ability, allows the user to choose a new ability from a list of 8.

---

### Proposed:

1500 gold
Active: allows the user to select an ability to unlearn. Grants them a random ability in its place.

---

**Reasoning:** currently, torn page of retraining is a very "last resort" item. Since it has a high chance of fucking you over instead of helping, usually when players get one of them, they just sell it for a small gold boost.

This rework would make torn pages a stronger comeback mechanic, while also making them feel better to use. Nothing worse than losing the single good ability in your build due to a unlucky roll.

**Comment by darklordabc** [comment]
Item has been removed from game
