### ISSUE TITLE
Having 2 of the same hero in a game might allow those player's to control each other's hero

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#278]
I've never experienced this before however I've never specifically tried to do this.

![image](https://user-images.githubusercontent.com/63279022/85412036-7a5ae100-b5ac-11ea-9d26-929c1ca3fa38.png)

**Comment by SanctusAnimus** [comment]
Two same heroes are not supposed to be picked in a single game in the first place

**Comment by Draze22** [comment]
They can and often are.

**Comment by Draze22** [comment]
Possibly due to hero re-rolls

**Comment by Draze22** [comment]
Pretty sure this has been fixed.
