### ISSUE TITLE
Bugged spirit siphon charges 

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#292]
![image](https://user-images.githubusercontent.com/63279022/85970595-48170c80-ba0e-11ea-8112-adc2a07d423b.png)
![image](https://user-images.githubusercontent.com/63279022/85970255-413bca00-ba0d-11ea-8a74-6f50c00757d0.png)

**Comment by SanctusAnimus** [comment]
well refresher restores all charges on purpose when used, and i can't make multicast to restore charges for me. if refresher is multicasted (but it's now disabled) it would be possible to have a gap to cast more and more inbetween.
no longer replicates for me in any way though
