### ISSUE TITLE
Creeps need to be forced back into their arena if they leave.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#299]
![image](https://user-images.githubusercontent.com/63279022/86184748-276ac600-bb78-11ea-8715-9ad7ab161916.png)
![image](https://user-images.githubusercontent.com/63279022/86184815-410c0d80-bb78-11ea-94aa-749b2070d388.png)

**Comment by fcalife** [comment]
Should be fixed, would like confirmation

**Comment by Draze22** [comment]
I can quite confidently confirm that this works from my own experience while playing and the lack of new bug reports on this issue.
