### ISSUE TITLE
Tempest double sometimes dies immediately after being cast

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#305]
![image](https://user-images.githubusercontent.com/63279022/86547157-5f5c7980-bf7b-11ea-8fbe-a57e99c0ab59.png)

**Comment by Wintarogar** [comment]
In particular, this happened after the death of the creep and the rebirth of the ultreme wrait king

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/86524695-37104480-bec1-11ea-9985-fbf949558050.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87268940-2a1dd180-c50f-11ea-9b7d-4054716c2a1a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87369529-18e2cc80-c5c4-11ea-8c37-6e45b0486f01.png)
![image](https://user-images.githubusercontent.com/63279022/87369550-239d6180-c5c4-11ea-996d-804450ff68a7.png)

**Comment by SanctusAnimus** [comment]
Reopen if reoccurs
