### ISSUE TITLE
Mass serpent wards don't get cleared from the duel arena

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#307]
Mass serpent wards are one spell that can still be present in multiple duels and affect the outcome of duels the caster is not present in.

![image](https://user-images.githubusercontent.com/63279022/86500636-de17b200-bdd5-11ea-936c-27f30f968d31.png)
![image](https://user-images.githubusercontent.com/63279022/86500658-fe477100-bdd5-11ea-879c-adf331b6c26f.png)

**Comment by SanctusAnimus** [comment]
Works fine for me, properly cleaned up from duel arena
