### ISSUE TITLE
Year of the Beast typo

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#314]
![image](https://user-images.githubusercontent.com/63279022/87236371-09c91680-c42c-11ea-93ec-20008e98a59a.png)

Should potentially even say 'Nian' instead of 'Year of the Beast' in all of the ability descriptions.

![image](https://user-images.githubusercontent.com/63279022/87236377-1cdbe680-c42c-11ea-9a21-87962a51ba07.png)

**Comment by Flam3sDOTA** [comment]
Fixed https://github.com/dota2unofficial/custom_hero_clash/commit/aba8c51a0f2ec9f5a707277f51f6e291fd2b2067
