### ISSUE TITLE
Re-rolling a hero category (attribute) mutliple times can give the same hero multiple times.

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#320]
This reduces the value of hero re-rolls and is generally frustrating for players.

**Comment by Draze22** [comment]
A particularly potent example of this is I got Magnus then Huskar then Magnus then Huskar.

**Comment by Sheodar** [comment]
It's not a bug. It's just random. For now we have system:
3 heroes for each player, and 30 heroes for randoming (10 for each stat). When u reroll hero, system give u new hero and get your old hero in main pull. 
If we will implement system with no-doubled hero we should choose 1 option:
 - Increase main hero pull. (from 30 to 60 heroes min) +20 checks
 - Add checker. When i reroll hero. If pull has hero whom I haven's seen, pull will get me this hero. But if pull doesn't have hero whom I haven's seen, it will get me totally random hero (whom i could see before) 
I like second option. Maybe little collaboration with the 1st option. Increase pull from 30 to 45 heroes and implement system from the 2nd option.

**Comment by Sheodar** [comment]
Fixed (more info in commit)
