### ISSUE TITLE
Game didn't end when there was 1 player left alive

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#325]
Appears to be caused by the bug where a dead player that never picked a hero is higher on the scoreboard than they should be.

![image](https://user-images.githubusercontent.com/63279022/87621037-4a45ce80-c763-11ea-87e3-7963f638281d.png)
![image](https://user-images.githubusercontent.com/63279022/87621064-5467cd00-c763-11ea-9822-ca07cc77afc6.png)

**Comment by AustraliaIsMyCity** [comment]
This is caused by https://github.com/dota2unofficial/custom_hero_clash_issues/issues/384, move all discussion to that thread
