### ISSUE TITLE
Hidden unit/s attacking heroes in their pve arena

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#329]
![image](https://user-images.githubusercontent.com/63279022/87739898-48900f80-c824-11ea-995c-5a9a4be27300.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87740464-a1ac7300-c825-11ea-8e79-7d2363c167fd.png)
![image](https://user-images.githubusercontent.com/63279022/87740524-c1439b80-c825-11ea-9828-943b03341ca1.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/87843295-b3aa1680-c8f6-11ea-910a-5dac36f39a80.png)

**Comment by SanctusAnimus** [comment]
Should be fixed
