### ISSUE TITLE
Left hand side player icons are not showing up in bottom-right duel UI history

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#341]
![image](https://user-images.githubusercontent.com/63279022/87867164-b88dc980-c9cd-11ea-8fcd-fb0ab7f0b829.png)
![image](https://user-images.githubusercontent.com/63279022/87867153-93995680-c9cd-11ea-94b8-bb723e051f16.png)

**Comment by SanctusAnimus** [comment]
is this still an issue? can't replicate, reopen if has specific steps
