### ISSUE TITLE
Player view automatically shrinks when duel bet window appears

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#346]
![image](https://user-images.githubusercontent.com/16277198/87906299-bd25b100-caa5-11ea-9a4d-9ca14c385697.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/mto1Qq1y) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Is this still an issue?

**Comment by SanctusAnimus** [comment]
Duplicate
