### ISSUE TITLE
Sometimes talents dont display properly in the UI

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#35]
![image](https://user-images.githubusercontent.com/50186248/78629775-5f48d100-78db-11ea-8733-626dfb8675c3.png)
I (witch doctor) have the +6 armor but for me it doesnt display it. Other players see it as 8+6 armor

**Comment by Sheodar** [comment]
It was dota's problem (some talends didn't display in dota lobby). For now all works fine (i hope). Open this issue again, if u'll see this error again.
