### ISSUE TITLE
Unsable concoction with no cooldown or manacost

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#351]
![image](https://user-images.githubusercontent.com/63279022/88368270-08ef9780-cdd1-11ea-908a-56fb752e29d5.png)
![image](https://user-images.githubusercontent.com/63279022/88368277-0e4ce200-cdd1-11ea-812b-c685c1fa376a.png)

**Comment by SanctusAnimus** [comment]
Should be fixed
