### ISSUE TITLE
Wukong's command megathread

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#352]
* [x] Summons units in the wrong place.

![image](https://user-images.githubusercontent.com/63279022/87865547-2203dd00-c9ba-11ea-8ba4-6d2624dc7728.png)
![image](https://user-images.githubusercontent.com/63279022/87865582-7c9d3900-c9ba-11ea-874d-a93176ae25a7.png)
This indicates that this bug relates to issue #329.

┆Issue is synchronized with this [Trello card](https://trello.com/c/mqV6uZhx) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/88368378-494f1580-cdd1-11ea-9181-519d1d71eea3.png)
![image](https://user-images.githubusercontent.com/63279022/88368396-5409aa80-cdd1-11ea-92d2-6359af3dcae1.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/88368930-54567580-cdd2-11ea-9ed4-197449d8529f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/88368943-5c161a00-cdd2-11ea-836a-acf6191e82fc.png)

**Comment by SanctusAnimus** [comment]
Fixed everything except for gold from duel - wasn't able to replicate properly with bots, and hard to tell any possible reason for such behaviour

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/88471035-2cd4e980-cf47-11ea-88f9-d46fb3ca8b56.png)

**Comment by SanctusAnimus** [comment]
Fixed

**Comment by Draze22** [comment]
Another report of Wukong's Command giving extra gold in duels.

![image](https://user-images.githubusercontent.com/63279022/89127483-1de6cc00-d531-11ea-9cb9-5dfe131c0a98.png)

**Comment by SanctusAnimus** [comment]
Does it counts towards barrage bullets/history/bets/whatever or as flat hero kill gold?

**Comment by Draze22** [comment]
Closing this for now.
