### ISSUE TITLE
Player was attackable after dying in a duel

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#353]
![image](https://user-images.githubusercontent.com/63279022/88368521-9cc16380-cdd1-11ea-9b01-e1e0163b5477.png)
![image](https://user-images.githubusercontent.com/63279022/88368744-02155480-cdd2-11ea-9b83-91d434c69a08.png)
![image](https://user-images.githubusercontent.com/63279022/88368561-b1056080-cdd1-11ea-8c8a-80edb6c53e15.png)
![image](https://user-images.githubusercontent.com/63279022/88369018-7a7c1580-cdd2-11ea-9c99-2c932e78d8c6.png)

**Comment by fcalife** [comment]
this looks like its venge's aghs scepter illusion?

**Comment by fcalife** [comment]
Assumed fixed by https://github.com/dota2unofficial/custom_hero_clash/commit/5d21dbe09550e3f26533dc5229297495acdf380d - same explanation given in #457 is valid here.
