### ISSUE TITLE
Some, if not all enemy units that spawn during overtime don't get buffed by it

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#355]
![image](https://user-images.githubusercontent.com/63279022/88396809-6225ee00-ce06-11ea-8161-3eacac737ec7.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/540abf4a84c3dca861beeef9d6e06190b8570ed3
