### ISSUE TITLE
Players are sometimes gaining a lot of extra gold from duels

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#357]
Edit: pretty sure this is due to very high kill bounties from players having very high networths and kill streaks.

It's unclear whether the extra gold is from winning the duel or from the kill bounty from killing their duel opponent and it's also not clear what specific circumstances this bug occurs under.

![image](https://user-images.githubusercontent.com/63279022/88448801-a8ba2d80-ce84-11ea-9ea9-3fb8d4f173b0.png)
![image](https://user-images.githubusercontent.com/63279022/88448806-b079d200-ce84-11ea-8f57-031fbf712716.png)

**Comment by AustraliaIsMyCity** [comment]
This is cause by wukongs. added to megathread

**Comment by Draze22** [comment]
Pretty sure this is due to very high kill bounties.

**Comment by Draze22** [comment]
Reopening until this can be confirmed.

**Comment by Draze22** [comment]
No more reports of this happening and I can confirm from my recent games that this hasn't been happening.
