### ISSUE TITLE
Picking terrorize gives bedlam which can then be retrained

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#360]
![image](https://user-images.githubusercontent.com/63279022/88756927-35782a80-d1a8-11ea-90fe-51d0a4cad5b3.png)
![image](https://user-images.githubusercontent.com/63279022/88756932-38731b00-d1a8-11ea-9bc3-70931ead371a.png)
If the abilities aren't linked in the CHC files it might have to do with them being linked in regular Dota.

**Comment by SanctusAnimus** [comment]
Well i couldn't replicate it niether via chat command giving ability nor with regular unmodified selection, it gave me a single ability

**Comment by darklordabc** [comment]
Requires buying aghs to trigger, but we have figured that out already.

**Comment by SanctusAnimus** [comment]
Fixed
