### ISSUE TITLE
Player managed to get attribute shift (agility) without attribute shift (strength)

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#361]
![image](https://user-images.githubusercontent.com/63279022/88880445-16dd6680-d270-11ea-9ded-e600d5ce8a01.png)

**Comment by AustraliaIsMyCity** [comment]
Title and screenshot are 2 different things, are you high @Draze22 ?

**Comment by AustraliaIsMyCity** [comment]
Also the bug in this case is probably just terrorize being a linked ability but still retrainable

**Comment by Draze22** [comment]
Fixed the image.

**Comment by Draze22** [comment]
Hasn't occured again.
