### ISSUE TITLE
Discarding sometimes makes players lose an ability

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#365]
![image](https://user-images.githubusercontent.com/63279022/88761670-ebe10d00-d1b2-11ea-85cb-941cc0dead36.png)

**Comment by AustraliaIsMyCity** [comment]
This is due to @darklordabc uhhh I mean an unknown developer changing `pudge_flesh_heap` to `pudge_flesh_heap_lua` without merging the flesh heap rework branch
