### ISSUE TITLE
Hero Panel shrinks (resizes) without clicking. 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#366]
Something causes this hero panel to always shrink, I havent paid enough attentiont yet to see when, but I think its related to duels. I've noticed it in tools and on workshop, it happens nearly every game, some event is making it resize, an event which isnt a player's mouse click.
![image](https://user-images.githubusercontent.com/16277198/88845500-9d218a80-d227-11ea-96ac-964ad67f6b9b.png)

**Comment by Draze22** [comment]
This got fixed or at the very least fixed in almost all circumstances.
