### ISSUE TITLE
Dead/Specating players cannot see bet windows

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#371]
Cannot see the bet window pre duel nor the bet window during the duel. The first one isnt that important, but they should be able to see the bet window that appears during duels. 
![image](https://user-images.githubusercontent.com/16277198/77990704-be539680-736d-11ea-9e05-0b578f421fbe.png)

**Comment by Draze22** [comment]
Moved to the spectator megathread (issue #356).
