### ISSUE TITLE
Clock conflicts with top buttons on some aspect rations

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#374]
![image](https://user-images.githubusercontent.com/16277198/80117383-79b4c700-85ca-11ea-926e-cb114f874bb3.png)

![image](https://user-images.githubusercontent.com/16277198/80117360-73264f80-85ca-11ea-9157-6214701835ea.png)
![image](https://user-images.githubusercontent.com/16277198/80117405-7e797b00-85ca-11ea-92d8-15a8bd4d3a53.png)

**Comment by SanctusAnimus** [comment]
Fixed
