### ISSUE TITLE
Strange Duo Bug, Creeps Wont Attack

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#379]
I started a duo game with 12 players (stupid host), the game is stupid so instead of combining us into one team, it put me (templar) and sniper into two separate times, the sniper disconnected and left. But now it places me and sniper into the same arena, even tho we attack each other when we spawn there because we are on separate teams. 
![image](https://user-images.githubusercontent.com/16277198/80895178-5bb33900-8d25-11ea-9056-0289c2d2208f.png)

Also when sniper does, the creeps stop attacking altogether and just jerk movement
![image](https://user-images.githubusercontent.com/16277198/80895150-05de9100-8d25-11ea-90e7-84abfea91d48.png)

![image](https://user-images.githubusercontent.com/16277198/80895157-1858ca80-8d25-11ea-9e97-ea11790f73fc.png)

Some fixes

- [ ] There should never be a game where there is two or more solo players in a duo mode. Game should always shuffle them into the team, this is a long standing problem.

- [ ] Abandonded players, should not be teleported into any arena, even if their ally is still alive (debatable). 

- [ ] It should not be possible for two heros, of diffrent teams to be teleported to same arena.

**Comment by SanctusAnimus** [comment]
Is this still an issue? Reopen if yes
