### ISSUE TITLE
We should probably not allow swapping spirit bear

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#383]
Swapping is problematic for the bear. You can swap the ability but the bear does not die straight away.  So it allows both heros to have bears. Also there is the case when swapping the bear ability, what about the items on the bear? Do we transfer them to the new bear? Do we refund them? Do we kill the bear? And if we kill the bear what about tricks players can use to keep the bear alive (like disruption)?

It seems it might be prudent to prevent swapping the ability if the player has used it once (to allow players getting to swap it at the begining of the game)/.

**Comment by Draze22** [comment]
Has this been disabled?

**Comment by Draze22** [comment]
Fixed in next update by @happyfeedfriends.
