### ISSUE TITLE
Compile all thinkers and evaluate their tick rate

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#388]
Timers:CreateTimer
OnChannelThink
CreateModifierThinker
StartIntervalThink
OnProjectileThink
SetContextThink

┆Issue is synchronized with this [Trello card](https://trello.com/c/WOjxcSWo) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
I already had a list of them here and it's not that important by itself? Performance doesn't really suffer from those, it's more about particles and entities cleanup

**Comment by SanctusAnimus** [comment]
Automatically gathered on server
