### ISSUE TITLE
2.0 issues

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#389]
### Critical bugs

- [x] Waves that can break the game by never ending:
 - [x] Monkey Menace
 - [x] Spawnmother
 - [x] Crystal Bug
 - [x] (presumed) Jabberwock when randoming Spawnmother abilities

- [x] Health-increasing totem breaks the Crystal Bug wave entirely
- [x] Monkey wave needs to be reworked, if players are too slow to kill it, it severely lags the game

### Balance

- [x] Creeps hit too hard starting roughly at wave 20+
- [x] (Australia is my City) Mud golem boss is too hard
- [x] Year Beast Overpower spell is too strong
- [x] Perma-dispel from wave 50+ is too strong
- [x] Summoned creeps are not inheriting true sight
- [x] Summoned creeps are not affected by the overtime buff
- [x] Odobenus Captain's ability does not update based on its level

### Other / QoL

- [x] Make it more obvious when a creep is Ancient (different health bars?)
- [x] Add 3-second countdown before pvp duels
- [x] Add panel showing the next wave's totem
- [x] Add panel showing the next wave's creep abilities
- [x] Improve boss wave previews (make them different from normal ones)
- [x] Add missing totem tooltips and effects
- [x] Reset players' MMR
- [ ] Make MMR gain/loss formula slightly more lenient

**Comment by Draze22** [comment]
All of the initial issues here have been implemented/fixed. Remade this issue into issue #554 and issue #555.
