### ISSUE TITLE
Warsong and Luminance

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#390]
**Luminance:** [11850]
Radiance [5150] + Blademail [2050] + Sange [2050] + Recipe [2600]

+ **100** Damage
+ **8** Armor
+ **20** Strength
+ **20%** Status Resistance
+ **35%** Self HP Regen and Lifesteal Amp

**Active: _Damage Return_** [25MP] [25CD]
For 4.5 seconds, duplicates **80%** of any damage taken back to the unit that dealt the damage.

**Passive: _Blaze_**
Scorches enemies for **100** plus a multiplier of your str as magical damage per second. Does triple damage if you have more str than int. Doesn't work on illusions. (is **not** affected by spell amp)
Strength round multiplier: **150%**
Strength duel multiplier: **75%**
Radius: 700

**Passive: _Damage Return_**
Every time you are attacked, you return a multiplier of your str plus 25% of the attack damage dealt to you.
Strength round multiplier: **125%**
Strength duel multiplier: **75%**

**Warsong** [12000]
Battle Fury [4180] + Monkey King Bar [4300] + Yasha [2050] + Recipe [1470]
+ **100** Attack Damage
+ **50** Attack Speed
+ **20** Agility
+ **30%** movement speed
+ **12** health regeneration
+ **6** mana regeneration
**Passive: _Cleave_**
Deals **85%** of attack damage as physical damage in a cone up to **650** around the target. (Melee Only)
**Passive: _Master of War_**
Grants each attack a **75%** chance to pierce through evasion, dealing **200** bonus magical damage in a cone up to **650**. (Cleave Damage is Melee Only)
Each proc gives a stacking buff providing + **3** agi for **10** seconds.
**Active: _Colossal Slash_** [125MP] [18CD] [Ground Target]
Launches a **225** radius shockwave in the target direction, which travels for **1400** units. Attacks enemies it passes through, with a guaranteed Master of War proc. Destroys trees in the path.

edit: updated items for 7.27

**Comment by fcalife** [comment]
Which version of Warsong will be considered?

**Comment by darklordabc** [comment]
This one
>warsong
>[butterfly + mkb + yasha stats]

> passive: swift strike - 75% chance to ignore evasion and hit the target with an extra attack on every attack. Extra attack deals 100 bonus magic damage and does not proc modifiers.
> 
> passive: riposte - dodging an attack causes the attacker to be affected by swift strike.

**Comment by fcalife** [comment]
Added in https://github.com/dota2unofficial/custom_hero_clash/pull/600
