### ISSUE TITLE
Betting rework

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#392]
**Old system:**
There is a set pot for a duel, players receive a percentage of it plus a percentage of the total bet amount based on how much they bet. Duel winner gets 100% of the amount bet (plus a pot?) if no one bets on them or 40% if anyone does. This means that if one person bets 1 gold on the winner they get 4k gold where they would have otherwise received 10k... not very fair.
**New system:**
Base pot = `1450 + 50*level + 0.5*level**2`
The winner automatically bets 
`<total amount bet>/(<number of players who bet>+1)+0.02*<base pot>`
on themselves (these are added to `<total pot amount` and `<total amount bet on winner>`).
Players win 
`<bet amount>*<total pot amount>/<total amount bet on winner>`
This means the duelist gains much more money as they didn't spend money on the bet.
The `+0.02*<base pot>` is added to prevent players from betting one gold to take the pot.
When `<base pot> = 1000` the duelist automatically bets 20 on themselves so if a player bets 1 on them they'll only get 47 profit whereas the duelist will gain 993.

**Comment by fcalife** [comment]
This is outdated. @AustraliaIsMyCity please open a new issue with your current bet rework concept, I know there is one.
