### ISSUE TITLE
Review and Add New Hints

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#393]
"LoadingTip_1"				"You can use custom chat wheel in game (Press L). It has some cooldown for use."
		"LoadingTip_2"				"You can center camera on your hero by double clicking any hero icon."
		"LoadingTip_3"				"When duel round time expires, the player with higher HP percentage will win."
		"LoadingTip_4"				"If one player wins a Duel, but no player bet on them, they will win Jackpot."
		"LoadingTip_5"				"Some creatures will gain true sight from Round 10."
		"LoadingTip_6"				"Kaya can be upgraded to Sky Force staff."
		"LoadingTip_7"				"You can buy attribute books from the shop, if you have too much gold to spend."
		"LoadingTip_8"				"There is an options menu next to the minimap. You can change camera and other settings. Settings are synched between games."
		"LoadingTip_9"				"If you do not get abilities when picking or when you use a book item or you see other player’s model as empty box, exit the game and reconnect to fix it."
		"LoadingTip_10" 			"You can disable the camera automatically moving to the duel by clicking the checkboxes above the minimap."
		"LoadingTip_11" 			"In Duo Mode you can press F7 to swap abilities with your teammate."
		"LoadingTip_12" 			"You can purchase Book of Paragon to give you a 6th ability."
		"LoadingTip_13" 			"Report all bugs and suggestions to Steam Workshop or Discord."
		"LoadingTip_14" 			"Replica Rackatee is a new purchasable item that gives splash damage to ranged units."
		"LoadingTip_15" 			"Most Summons can be buffed with Mask of the Dominator."
		"LoadingTip_16"             "You gain +0.2% spell amp per intelligence, and +0.6% while fighting neutrals."
		"LoadingTip_17" 			"Spell amp and manacost/manaloss reduction from items (e.g. Starforce) does not stack."
		"LoadingTip_18" 			"There is a 65% chance for one of your hero's abilities to appear when drafting. 100% chance on first draft."
		"LoadingTip_19" 			"A Roshan fight will replace a random neutral wave from round 41 to round 50."
		"LoadingTip_20" 			"Rounds 1 to 10 have a chance of dropping tier 1 neutral items. Round 11 to 20 chance to drop tier 2, etc."
		"LoadingTip_21" 			"Neutrals gain health, damage, spell amp and status resistance as the rounds progress."
		"LoadingTip_22" 			"When the round timer expires neutrals will rapidly gain damage, status resistance, and move/attack speed, while also stripping your armour."
		"LoadingTip_23" 			"At rounds 10 and 20, the bottom 3 networth players are given Retraining items."
		"LoadingTip_24" 			"All-Talk is enabled in FFA. You can use a mic to talk to everybody."
		"LoadingTip_25" 			"Early Duel Items: Faerie Fire, Mango, Sentry Ward/Dust."
		"LoadingTip_26" 			"Become a Founder and support us on Patreon. Unlocks Cosmetics Menu. Only 3 dollars a month."
		"LoadingTip_27" 			"Mousing over the hero icon during hero pick phase will show detailed stats."
		"LoadingTip_28" 			"You can view a history of recent events by clicking the button next to minimp."
		"LoadingTip_29"				"You can alt-click abilities on the bet window to warn other players about them."

**Comment by Draze22** [comment]
We added a channel to the community discord where players made suggestions for changes to existing hints and for new ones. I reviewed these, used the suggestions I thought made sense and also made a few alterations of my own.

**Comment by fcalife** [comment]
Updated
