### ISSUE TITLE
New Innate Ideas

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#395]
Barbarian: 40+ Strength
![image](https://user-images.githubusercontent.com/16277198/86712549-745f0880-c060-11ea-8879-a879f0e8ca95.png)

Flash: 40+ Agility
![image](https://user-images.githubusercontent.com/16277198/86712711-a40e1080-c060-11ea-970d-f644157979ea.png)

Flexible: Gain one book of retraining after losing a duel
![image](https://user-images.githubusercontent.com/16277198/86712931-e2a3cb00-c060-11ea-8a4c-118ff5d1c8a6.png)

Winner: Every time you win a duel your overall damage output is increased by 2%
![image](https://user-images.githubusercontent.com/16277198/86713271-3f06ea80-c061-11ea-8ce4-95bec1bcc4ca.png)

Slippery - "Gain the ability to walk through creeps (Like phase boots), also gaining 10% evasion" Combine with that other perk we have

Momentum - Every time you win a Duel gain 3 Permanent to your primary attribute. If you won your previous duel, other attributes also gain a bonus equal to 1/3 of your current permanent gain.
![image](https://user-images.githubusercontent.com/16277198/86713558-89886700-c061-11ea-9269-c5d1e9aa1dac.png)

Studious - Start with an extra Tome of Retraining.
![image](https://user-images.githubusercontent.com/16277198/86713810-ceac9900-c061-11ea-9821-c9e4131c85d7.png)

Cleave - 30% Cleave Damage
![image](https://user-images.githubusercontent.com/16277198/86714121-1e8b6000-c062-11ea-94fd-67d5ca700847.png)

Revenge - When you lose an aegis in a creep round, it will cause an explosion killing all remaining creeps, including bosses
![image](https://user-images.githubusercontent.com/16277198/86714299-5b575700-c062-11ea-872f-80af5f17ffe2.png)

One Man Army - Illusions deal 25% more damage
![image](https://user-images.githubusercontent.com/16277198/86714606-b0936880-c062-11ea-9f90-06dbf9c7820f.png)

Rage of Poverty - Deal 30% more damage when money is below 1000
![image](https://user-images.githubusercontent.com/16277198/86715114-3dd6bd00-c063-11ea-8144-3b26fb6eebe7.png)

Challenger - can mark themselves as ready to duel, the next duel that occurs will include them, limit 1 use per cycle or per 5 rounds.
![image](https://user-images.githubusercontent.com/16277198/86715378-842c1c00-c063-11ea-8a21-b35541a640fe.png)

Extra Delivery - Can choose from 6 neutral items instead of 3
![image](https://user-images.githubusercontent.com/16277198/86715762-e2f19580-c063-11ea-9ef9-d0d33c93f7c0.png)

**Comment by fcalife** [comment]
Barbarian: implemented

Flash: implemented

Cleave: implemented

Slippery; trickster covers this in every way

Flexible: overpowered

Rage of Poverty: boring, its war veteran but only works after you purchase an item, prevents you from betting effectively, works against the player overall

Challenger: abusable, let's not

Would you like to implement Winner, Momentum, Studious, Revenge, One Man Army, and Extra Delivery?

Winner and Momentum could probably be combined into a single ability.

Need more opinions on this.

**Comment by darklordabc** [comment]
Those 6 innates are enough i reckon.

**Comment by fcalife** [comment]
@Draze22 @AustraliaIsMyCity get in here

**Comment by Draze22** [comment]
- Winner needs a buff to 2.5-3%.
- Momentum needs a buff, I'd make it like 3 primary 1 of each secondary for a win which increases by 3,1,1 for each consecutive win (should be underpowered on average still).
- Studious should be 2 retraining books.
- Revenge should be decent
- Is one man army a flat 25% increase or a percent 25% increase?
- Extra delivery should also let you choose from neutral items of the tier above but maybe only give you 1-2 extra choices.

**Comment by Draze22** [comment]
Break: 4 second duration break on hit, 10 second cd.

**Comment by fcalife** [comment]
Implemented in https://github.com/dota2unofficial/custom_hero_clash/pull/602/commits/bf67ee96c8289b244240ffc1693b2725fdbcf802
