### ISSUE TITLE
Localization Issues

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#396]
Not in Chinese and I assume not in Russian
![image](https://user-images.githubusercontent.com/16277198/87854782-935e7400-c957-11ea-817a-4c26ab973bb3.png)
The text in these gold counter windows
![image](https://user-images.githubusercontent.com/16277198/87854816-c0128b80-c957-11ea-9945-ded484439e18.png)

**Comment by fcalife** [comment]
Fixed on https://github.com/dota2unofficial/custom_hero_clash/commit/d9dac76a1101f2b9d9c933dada1f21eb0bb4b602

Left tokens in english on the chinese file, translated them with deepL on the russian one.
