### ISSUE TITLE
Fix Portraits

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#397]
![image](https://user-images.githubusercontent.com/16277198/87855096-657a2f00-c959-11ea-9dbf-f52e5b50964a.png)

**Comment by fcalife** [comment]
@Sheodar all of them are fixed except for this one:

![chrome_mO9XkaHdiI](https://user-images.githubusercontent.com/7921728/88511240-e325e680-cfba-11ea-9d11-616f94c7780f.png)

It's the last skeleton from the skeleton round (after it revives 3 times). npc_dota_skeleton_rerereincarnated :D

Great job btw. The portraits look **_sick._**

**Comment by Sheodar** [comment]
Oh. I tried find this skeleton. Thanks for name :D I'll add it little later.

**Comment by Sheodar** [comment]
Fixed skeleton.
