### ISSUE TITLE
Add Stat tracking for items too

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#400]
Add most picked and most successful items to this page

**Comment by Draze22** [comment]
If you're including the backpack you should also include the stash.

**Comment by SanctusAnimus** [comment]
@ark120202  i've added item tracking to webapi, ping me if you are not ok with names or anything, 
commit https://github.com/dota2unofficial/custom_hero_clash/commit/7ff2d2b15dfdfaa37e0a945906e208566e281556

**Comment by SanctusAnimus** [comment]
this one does include backpack but not stash (since we only discussed backpack and adding stash should be easy afterwards)

**Comment by Draze22** [comment]
Is this fully implemented?

**Comment by SanctusAnimus** [comment]
why is this reopened, it's done long time ago
