### ISSUE TITLE
Small window where players can die after they have defeated a creep round causing bugs

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#401]
One fairly major bug that's been ignored for a while is there is a small amount of time after killing the final creep in a round where the round has technically finished but you can still take damage. This causes a couple of bugs where players die and respawn in their creep arena (if they have an aegis) or don't respawn (if they don't have any aegises). And if they don't respawn and are also put in a duel the next round they are dead in the duel which last the full 50 seconds giving the win to a random player. After the duel the dead player respawns in the fountain but doesn't participate in the game from then on.

**Comment by Draze22** [comment]
This is a description of issues #51 and #203.

**Comment by SanctusAnimus** [comment]
Technically should be fixed, reopen if reoccurs
