### ISSUE TITLE
Using the reroll function while choosing an ability removes the discard function

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#407]
![image](https://user-images.githubusercontent.com/63279022/88883880-b3a40200-d278-11ea-8035-f48ed9793379.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/89866626-3753dc00-dbf3-11ea-8777-ac02af7dd366.png)
![image](https://user-images.githubusercontent.com/63279022/89866638-3cb12680-dbf3-11ea-9508-fcb411a0c1d3.png)

**Comment by SanctusAnimus** [comment]
should not be the case after i've disabled animation on that one. Can't reproduce it anyway
