### ISSUE TITLE
Getting more than 6 abilities

### ISSUE THREAD

**Issue by Bruno-SW** [dota2unofficial/custom_hero_clash_issues#408]
This player had 8 abilities, 2 which added aditional due to aghanim, leading to a total of 10 abilities, when confronted he claimed not to known how he got them, i suspect that he could retrain terror wave as i saw he using a retraining book and the ability terror wave reapeared in his spell slots after one ability had been choosen. If he could do that because he was terror blade it might happen the same thing with other abilities on it's original hero, if i'm lucky ill try and replicate the issue for "research purposes". And for those wondering he still lost the game ahahah.

![image](https://user-images.githubusercontent.com/69020186/88984638-7fded180-d2a4-11ea-95d1-401b839e2502.png)

**Comment by SanctusAnimus** [comment]
Should be resolved in next update

**Comment by Bruno-SW** [comment]
I could not reproduce the issue
