### ISSUE TITLE
Unstable concoction throw can be manipulated to be a seperate ability which then has no cd

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#411]
This probably just occurs when the player moves their skills around while unstable concoction is being brewed (after being activated but before being thrown).

![image](https://user-images.githubusercontent.com/63279022/89001829-ae10ef80-d33e-11ea-81ff-38eab87d38d0.png)
![image](https://user-images.githubusercontent.com/63279022/89001834-b10be000-d33e-11ea-8115-b81c51142cad.png)

**Comment by darklordabc** [comment]
Can confirmed, easily reproducible.

**Comment by SanctusAnimus** [comment]
Fixed
