### ISSUE TITLE
Killing tempest double in duels can count as a kill

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#412]
This isn't a big deal since it just gives the player who did it a bit extra gold.
![image](https://user-images.githubusercontent.com/63279022/89002015-53c45e80-d33f-11ea-8e24-5515b19691f1.png)
![image](https://user-images.githubusercontent.com/63279022/89002026-5cb53000-d33f-11ea-8538-73f014a89880.png)

**Comment by SanctusAnimus** [comment]
technically you shouldn't be able to kill it as it has min health of 1 set, so it's pretty strange

**Comment by SanctusAnimus** [comment]
no more confirmations on this? reopen if anything, but tempest double should never die completely to count as a kill
