### ISSUE TITLE
Broken score board

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#413]
![image](https://user-images.githubusercontent.com/63279022/89002997-ec5bde00-d341-11ea-8d23-36e5c0d3a22a.png)
![image](https://user-images.githubusercontent.com/63279022/89003003-f4b41900-d341-11ea-8865-8aeb9caf7fa6.png)

**Comment by Shushishtok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Broodmother spawn spiders damage talent doesn't work #746](https://trello.com/c/hw8VcxEL/217-broodmother-spawn-spiders-damage-talent-doesnt-work-746)
