### ISSUE TITLE
Ranks are not showing for squads

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#415]
![image](https://user-images.githubusercontent.com/16277198/89066989-c5d58b80-d3b1-11ea-9660-dabb87d05e41.png)

The problem also exists on the server
![image](https://user-images.githubusercontent.com/16277198/89067002-ca9a3f80-d3b1-11ea-8d67-f9104ea4186d.png)

**Comment by SanctusAnimus** [comment]
iirc fixed long time ago?
