### ISSUE TITLE
Ranks are not showing in scoreboards

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#416]
![image](https://user-images.githubusercontent.com/16277198/89067553-dafeea00-d3b2-11ea-9d87-97003b59630f.png)
![image](https://user-images.githubusercontent.com/16277198/89067561-dd614400-d3b2-11ea-912c-cfe528d5485c.png)

**Comment by Sheodar** [comment]
Fixed

**Comment by Sheodar** [comment]
Need update table "match_rating_info" in server side. But need upated code for first.

**Comment by Draze22** [comment]
Sounds like this has been fixed.
