### ISSUE TITLE
In the greevil bonus round, only hero that kills greevils get the above head gold

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#417]
All teammates will get the gold reward, but only the player that actually kills the big gold greevil will see the gold popping out from his head. It should be popping out for all teammates. 
![image](https://user-images.githubusercontent.com/16277198/89076235-405ad700-d3c3-11ea-8d99-1049cc3172e4.png)

**Comment by fcalife** [comment]
The gold is shown on the top of each player's head, only to themselves. Showing all gold ticks to all players would cause severe ear rape, since each tick plays the 'ka-chink' coin sound.
