### ISSUE TITLE
Hide Rearrange Abilities and Transfer Ability button when viewing other units

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#418]
These buttons should only appear when you have your own hero selected. Currently it shows all the time, even when you are viewing creeps or other heros. 
![image](https://user-images.githubusercontent.com/16277198/89076324-62ecf000-d3c3-11ea-98fa-0eace8ba5897.png)

**Comment by SanctusAnimus** [comment]
Fixed
