### ISSUE TITLE
Stats is "lost" from Atribute shift when retrained

### ISSUE THREAD

**Issue by Bruno-SW** [dota2unofficial/custom_hero_clash_issues#419]
I had the Atribute Shift ability and maxed for str, i then retrained the ability and my stats got permanently shifted.

![image](https://user-images.githubusercontent.com/69020186/89102566-013b7e80-d3e1-11ea-9406-7fee1bf95335.png)

**Comment by Bruno-SW** [comment]
How to tag the issue?

**Comment by SanctusAnimus** [comment]
Wdym, they left shifted? It works same in dota with rubick, so it's not a bug really

**Comment by Bruno-SW** [comment]
Yes, left shifted, i wouldn't say it's a bug, perhaps an abuse since you could have str for free for the "luminance + flesh golem meta"

**Comment by Draze22** [comment]
There should be a tooltip that explains this interaction.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/89105036-3a1b3800-d461-11ea-8668-ac71031b6a0f.png)
