### ISSUE TITLE
Who is causing the lag in duos and especially in squads?

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#421]
The main suspect right now is lowered attack speed (So we may be addding back attack rate limit). Does anyone else have any theory?

**Comment by Draze22** [comment]
Closing this for now since lag has been reduced a lot.

**Comment by dym-sh** [comment]
maximum lag on drow ulti + void bash – enough chance to perpetuate near infinite loop on a single attack-reapply

also shaman wards with aghs
