### ISSUE TITLE
Player's losing skills from retraining

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#423]
Unclear what the exact circumstances that cause this bug to occur are.

![image](https://user-images.githubusercontent.com/63279022/89127529-71f1b080-d531-11ea-93d0-6a445ee868a1.png)

**Comment by Draze22** [comment]
This might be related.

![image](https://user-images.githubusercontent.com/63279022/89497383-984c7000-d7ff-11ea-84eb-67691ab3fcb9.png)
![image](https://user-images.githubusercontent.com/63279022/89497508-d21d7680-d7ff-11ea-8203-75cfc039669a.png)

**Comment by SanctusAnimus** [comment]
Without any steps to replicate, cannot fix. Closing for now
