### ISSUE TITLE
All creeps need to gain true sight during overtime including creeps that spawn during overtime

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#425]
Basically this prevents players from being able to stall certain rounds with invis and also helps with some rare cases where players want to be hit while invisible. 

![image](https://user-images.githubusercontent.com/63279022/89148081-11e42400-d59c-11ea-9177-1c1a56ba8328.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/540abf4a84c3dca861beeef9d6e06190b8570ed3
