### ISSUE TITLE
Players getting more than 6 abilities

### ISSUE THREAD

**Issue by kdfhockey1** [dota2unofficial/custom_hero_clash_issues#432]
![image](https://user-images.githubusercontent.com/69372608/89697278-78917680-d8e9-11ea-90dc-09f2ca41edda.png)
![image](https://user-images.githubusercontent.com/69372608/89697312-a1b20700-d8e9-11ea-89c0-ebb6a970902f.png)

See attached images for bug / abuse - both team mates 10+ abilities

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/89866931-b9440500-dbf3-11ea-9d88-93b6920716aa.png)

**Comment by Draze22** [comment]
Only happens in duos which means it has something to do with players swapping skills with each other.

**Comment by Draze22** [comment]
Seems to have been fixed.
