### ISSUE TITLE
Summoner (dominator) items don't give bonus damage

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#434]
![image](https://user-images.githubusercontent.com/63279022/90103051-39e63b00-dd85-11ea-9527-a7d08c8ed527.png)
![image](https://user-images.githubusercontent.com/63279022/90103066-3f438580-dd85-11ea-9d92-34bd059e8e14.png)

**Comment by SanctusAnimus** [comment]
Iirc @Sheodar changed it to be via damage filter, so damage is applied on attack, but not displayed in HUD?

**Comment by Draze22** [comment]
This is very confusing for players, so if it isn't necessary it should be reverted.

**Comment by SanctusAnimus** [comment]
IIRC it was made to allow skeletons and such to also have damage, cause it's a bit hard to make them inherit summoner buff in usual way

**Comment by Sheodar** [comment]
sketons/dots/wards damage/maybe other problem. Need check how we could get around it (maybe add bonus only in client side, but not server)
