### ISSUE TITLE
Various creep waves instantly get overtime buffs 

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#435]
![image](https://user-images.githubusercontent.com/63279022/90103291-9a757800-dd85-11ea-9a11-43b2461d1253.png)
![image](https://user-images.githubusercontent.com/63279022/90103613-25567280-dd86-11ea-8746-d8dfd83b39df.png)
![image](https://user-images.githubusercontent.com/63279022/90103633-30110780-dd86-11ea-835f-84622cd6d7a5.png)

**Comment by fcalife** [comment]
this was fixed on the patch after it was introduced
