### ISSUE TITLE
Spectators can't see most of the UI

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#439]
https://cdn.discordapp.com/attachments/694440472273354762/744236145067556884/20200816024002_1.jpg
Missing:
Hero UI on the left
Duel UI
Betting UI (should show up in the same way as it would for the duelists)

**Comment by AustraliaIsMyCity** [comment]
also lower priority but ability selection menus could also be shown

**Comment by Draze22** [comment]
Seems unnecessary.

**Comment by Draze22** [comment]
Added to issue #356.
