### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#440]
- [ ] Rework 50+ scaling
- [x] Increase duel effect on games
- [ ] Rework betting algorithm as proposed in [#392](https://github.com/dota2unofficial/custom_hero_clash_issues/issues/392)
- [ ] Add Warsong
- [x] Rework starforce
- [x] Nerf % based abilities
- [x] Disable borrowed time, bad juju, reincarnate and battle trance from being obtained together
- [x] Fix overtime not killing players sometimes
- [x] Fix scoreboard for spectators
- [x] Fix duel UI for spectators
- [x] Fix betting UI for spectators

After these things are completed I will host an FFA tournament with a ~$500 USD prize pool

**Comment by darklordabc** [comment]
Outdated
