### ISSUE TITLE
Ballista Bug 

### ISSUE THREAD

**Issue by AbdoNashaat** [dota2unofficial/custom_hero_clash_issues#441]
A ranged hero can push the neutrals outside the arena boundary and they cant move again. 
A player did that and after the over time passed nothing happened and since he cant kill it and doesn't want to die, he just stood there and did nothing and the neutral kept getting stronger but they cant move so we were stuck

**Comment by darklordabc** [comment]
Pretty sure this was fixed, @fcalife close if its done

**Comment by Draze22** [comment]
No longer an issue since ballista no longer has knockback.
