### ISSUE TITLE
Spirit bear dies instantly when summoned

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#442]
![image](https://user-images.githubusercontent.com/63279022/90438838-efafe180-e117-11ea-8e30-b62d6b9ec8a8.png)
![image](https://user-images.githubusercontent.com/63279022/90853176-b4820c80-e3bc-11ea-921b-0819f69c63b3.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/91164792-00adb380-e713-11ea-8e85-40d1cd430079.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/92292684-d3a69f80-ef61-11ea-9ce0-4f7dc0cc8166.png)

**Comment by Draze22** [comment]
Possible causes: 
Bear dies during a duel - [ ] 
Caused by aghanim's scepter or not having one - [ ] 
Caster dies while mid cast point of summoning bear - [ ] 
Re-summoned during a duel - [ ] 
Not being or being lone druid (having talents that upgrade bear) - [ ] 
Having a specific innate - [ ] 
- [ ] 
- [ ]

**Comment by darklordabc** [comment]
Outdated
