### ISSUE TITLE
Overtime causes abilities such as windrun, ghost shroud, ghost scepter, etc to have a significantly shorter duration

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#443]
![image](https://user-images.githubusercontent.com/63279022/90624698-b5e7f380-e25b-11ea-8da9-dd353ebb37be.png)

This can happen on any round.

**Comment by Draze22** [comment]
https://streamable.com/chbule

**Comment by HappyFeedFriends** [comment]
Need more information

**Comment by Draze22** [comment]
Haven't had any recent complaints about this.

**Comment by fcalife** [comment]
Overtime does apply purge on heroes once per second. Should this behavior be removed?

**Comment by fcalife** [comment]
No longer relevant after https://github.com/dota2unofficial/custom_hero_clash/pull/595 is merged
