### ISSUE TITLE
The game often freezes just before post wave 150 rounds start

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#446]
![image](https://user-images.githubusercontent.com/63279022/90853043-6c62ea00-e3bc-11ea-80b0-cd79e1b94f8e.png)
![image](https://user-images.githubusercontent.com/63279022/90853055-6ff67100-e3bc-11ea-8045-d5bbba7b5abd.png)
![image](https://user-images.githubusercontent.com/63279022/90853032-68cf6300-e3bc-11ea-9af7-b04e5f13a8b7.png)

**Comment by fcalife** [comment]
Need confirmation that this is still relevant, since later wave logic has been changed considerably since the day this issue was posted.

For now, performed a basic test on tools mode and the game progressed smoothly from 149 all the way to 170. Considering this solved unless re-opened.
