### ISSUE TITLE
False promise can make tempest double invulnerable

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#449]
![image](https://user-images.githubusercontent.com/63279022/91165870-ce04ba80-e714-11ea-88bd-8adb3673cb6f.png)

**Comment by HappyFeedFriends** [comment]
need more information

**Comment by fcalife** [comment]
Assumed to be integer overflow or bad false promise interaction with tempest double ending. Unable to verify or reproduce in tools.

**Comment by Draze22** [comment]
Closing this for now since it wasn't reproducible.
