### ISSUE TITLE
Avoid overlapping skill selection section on top of shop tab 

### ISSUE THREAD

**Issue by cenalulu** [dota2unofficial/custom_hero_clash_issues#453]
Just a suggestion. I normally hold my skill selection decision for couple of rounds and decides after seeing other opponent's skills  However the pending skill selection tab covers half of the shop tab which prevents me from performing most of the meaningful shopping operations when I'm holding the skill selection decision. Maybe better to move it to somewhere else like on top of the picked skilled bar or beneath the hero pic bar or even just overlapping with the leader board works better in this case.

**Comment by cenalulu** [comment]
Also great work on this MOD. More fun to play comparing to the custom hero chaos

**Comment by Draze22** [comment]
Could also make it so the shop UI is in front of the skill selection UI.

**Comment by AustraliaIsMyCity** [comment]
This has been fixed
