### ISSUE TITLE
Clear description on which skills belong to summon skill and can be enhanced by item 

### ISSUE THREAD

**Issue by cenalulu** [dota2unofficial/custom_hero_clash_issues#454]
[suggestion] Having played tens of games, I'm still not so sure about the full list of summon skills that can be buffed by summoner item. In general it would be useful to add tool-tips to those skill if they can. Would be very useful for noobs. 
Couple of ones that I'm still not unsure so far, hope we can get some clarification here: razor's eye of storm, techies' mines, weaver's swarm, ET's spirit, etc.

**Comment by Draze22** [comment]
Anything that can't be attacked doesn't get affected by it, weaver's swarm says it isn't and techies' mines don't although I'll have to check if they have a tooltip.

**Comment by Draze22** [comment]
Techies' mines also have tooltips stating they aren't buffed by crown of the dominator.
