### ISSUE TITLE
There is a very short period of time after being teleported to the fountain where player's can be killed

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#457]
![image](https://user-images.githubusercontent.com/63279022/92557786-5b691280-f2b0-11ea-8c93-2dfbdef521b6.png)

**Comment by fcalife** [comment]
Attempted a fix in https://github.com/dota2unofficial/custom_hero_clash/commit/5d21dbe09550e3f26533dc5229297495acdf380d - the invulnerability was already applied in the same frame as the teleport, I just made it do so even earlier, so I'm not 100% sure this changes anything. Basic testing involving ultra attack speed bots seems to point to this being solved; please revive the issue if that's not the case.
