### ISSUE TITLE
Tempest double stacks Essence Shift agility on creeps permanently

### ISSUE THREAD

**Issue by Qype** [dota2unofficial/custom_hero_clash_issues#458]
![1](https://user-images.githubusercontent.com/71134457/92928073-4672b780-f447-11ea-8b14-fbfc62bed851.png)
![2](https://user-images.githubusercontent.com/71134457/92928023-32c75100-f447-11ea-90c9-9339c9320221.png)

**Comment by Draze22** [comment]
Fixed.
