### ISSUE TITLE
Borrowed Time sometimes doesn't work

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#460]
A few players a while back reported taking damage during borrowed time during later rounds occasionally.

![image](https://user-images.githubusercontent.com/63279022/93010018-d8ef9400-f5ca-11ea-9e0c-9b3a16146c4a.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/93691453-a85aad80-fb28-11ea-8f56-ab1b122d29f4.png)

I also took damage during borrowed time while being attacked by summons.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/95142375-46a07180-07bf-11eb-9d0c-6250913f2072.png)

**Comment by SanctusAnimus** [comment]
probably has something to do with int overflow, untracable for me, and probably not something we can fix. closing for now
