### ISSUE TITLE
All creeps instantly dispell ghost scepter at level around 30 and above

### ISSUE THREAD

**Issue by RV281** [dota2unofficial/custom_hero_clash_issues#461]
i was playing tuskar with snowball, firestorm, rage and enrage. this thing happen, is this a feature or a bug? i dont know, i need answer

**Comment by Draze22** [comment]
A few people have reported a bug where once you have your ghost scepter dispelled during overtime it's duration is permanently shortened. There's also a creep round (Satyrs) that can dispel ghost scepter.

**Comment by HappyFeedFriends** [comment]
Ghost Scepter is scatterable for after time ends, as are many other positive effects.

**Comment by SanctusAnimus** [comment]
let's call that a "feature"
