### ISSUE TITLE
Issues related to new innates. 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#462]
- [x] Remove all the lore from innates, or add lore to all innates, I suggest remove.

- [x] **Rend**
Not sure if rend has an on-hit effect, but it should also have a debuff effect on the effected unit.
Also the ability does not say that each attack refreshes the cooldown, I expected it to act like bristle back with each hit having its own cooldown, please clarify that in the description. 

- [x] **Cleave**
You said you were going to reduce it to 40%, still 50, please lower it to 40. 

- [x] **Frenzy**
Remove the abbreviation from the description

- [x] **Capitalist**
This appears to trigger every time you level up, not necessarily at the end of rounds, which may lead to inconsistency later on if there is mechanics that allow a player to level up unrelated to round ending. Either actually make it round-based or reword the innate so it says level based. --was level based, is now round based

- [x] Also, there is no text saying "You gained x amount of interest", it only shows some gold numbers above the hero, but they wouldn't be able to tell how much they got in total. 

- [x] Also, some particle effects on the hero would be nice. 

 @fcalife or @Sheodar may need to help you on this one. 

- [x] **Fast Learner**
How is this coded? I tried testing it by using 'round -10' but did not gain any additional levels. I was not able to test this one. -- Same as capitalist

**Comment by AustraliaIsMyCity** [comment]
all done
