### ISSUE TITLE
Black hole aghs effect is affected by spell amp

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#463]
Black hole aghs applies midnight pulse damage which is a percentage damage spell. 
Currently it is affected by spell amp however all other percentage damage spell currently do not get affected by spell amp. 

It would be ideal if just the aghs midnight pulse damage wasn't affected by spell amp rather than just making the entire ability not get affected by spell amp.

**Comment by SanctusAnimus** [comment]
Happy tells me this is fixed, reopen if he's wrong

**Comment by SanctusAnimus** [comment]
ok happy lied to me

**Comment by Draze22** [comment]
Fixed (block hole isn't affected by spell amp if the player has an aghs).
