### ISSUE TITLE
Problem with a disconected player

### ISSUE THREAD

**Issue by parlandi** [dota2unofficial/custom_hero_clash_issues#466]
the player has no interest in this specific  match and quit, but he keep playing disconected and without a hero, every wave is simply ignored and the only choice we had was second place at best . the player was "Feljpe*"![image](https://user-images.githubusercontent.com/72486560/95291736-8d857a00-0846-11eb-97e9-99f232af7727.png)

**Comment by Draze22** [comment]
Duplicate of issue #384.
