### ISSUE TITLE
Aghanim's blessing innate doesn't give bonus aghs abilities

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#471]
People have reported not receiving swift slash and burrow.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/97794067-e16a5f80-1c48-11eb-8c1b-66f6bee61d8e.png)
![image](https://user-images.githubusercontent.com/63279022/97794069-e8916d80-1c48-11eb-9885-882475d11401.png)

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by Draze22** [comment]
This can also happen with the regular aghanim's blessing. 

In fact had this happen when i bought aghanim's blessing while already having omnislash. I initially got swiftslash but moments later when I tried to reorder my skills it disappeared.

![image](https://user-images.githubusercontent.com/63279022/98201046-f6196100-1f82-11eb-85a0-d7467eac7c13.png)

**Comment by fcalife** [comment]
Just confirming that this bug is related to aghanim's blessing in general and not only the innate

**Comment by SanctusAnimus** [comment]
On it

**Comment by SanctusAnimus** [comment]
Fixed innate, wasn't able to replicate anything with blessing itself, so reopen if reoccurs and have some way of reproduction
