### ISSUE TITLE
Can't control summons after dying in a duel in duos

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#472]
![image](https://user-images.githubusercontent.com/63279022/97655560-7a6a7080-1ab9-11eb-8d05-4160f5c86070.png)

I'm pretty sure I have been able to control summons after dying in duos but I could be wrong.

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/c023dbd1df99ba60fb804466c80c3f45b4dceefb
