### ISSUE TITLE
If natures prophet gets infernal blade from a discard it doesn't get affected by his cd reduction talent

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#477]
Not sure if this happens with other heroes with cd reduction talents getting infernal blade from a discard.

![image](https://user-images.githubusercontent.com/63279022/98063490-4bcb0c00-1ea4-11eb-9991-d557f2f7e407.png)

**Comment by HappyFeedFriends** [comment]
When checking, I did not find such problems.

**Comment by fcalife** [comment]
Unable to verify. Abilities (won via discard or not) are working normally with cooldown reduction, be them on furion or not,

Gonna call this one a weird visual bug and close it.

Fun fact: while trying to get infernal blade from a discard, I got both overwhelming odds and insatiable hunger a total of 4 times each.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/99867574-d59e0780-2c0e-11eb-84e7-dbd0238ab153.png)

Might be related.

**Comment by fcalife** [comment]
I honestly can't see a scenario in which this wouldn't just be a visual bug or where we would be responsible for it, unless talents are being removed by the hero builder. And in that case its a much deeper problem, not at all related to discarding. I'm gonna put this on the back of a hero builder rework and call it a day.

**Comment by Draze22** [comment]
Yeah, for sure seems like a visual bug.
