### ISSUE TITLE
There is no sounds on the betting interface, at all

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#485]
There is no sound feedback from clicking any of the buttons or moving the dial. Should have a ticking sound when you move the little dial thing.

**Comment by Flam3sDOTA** [comment]
Currently working on it.

**Comment by Flam3sDOTA** [comment]
can someone close this, I can't.

https://github.com/dota2unofficial/custom_hero_clash/commit/6dec055f62a391d93bf38416ea84a95848c43f5d
