### ISSUE TITLE
Necronomicon units aren't being killed properly after duels

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#493]
![image](https://user-images.githubusercontent.com/63279022/99602239-45689280-2a55-11eb-8e96-e93df0a0e5ff.png)
![image](https://user-images.githubusercontent.com/63279022/99602302-5addbc80-2a55-11eb-92b1-5e8fe84b3b56.png)
![image](https://user-images.githubusercontent.com/63279022/99602321-603b0700-2a55-11eb-8697-553cdffc683c.png)

**Comment by fcalife** [comment]
Attempted fix in https://github.com/dota2unofficial/custom_hero_clash/commit/ed2f4145d2702d55c4b7adef49813af286c6a44b
