### ISSUE TITLE
Make Decay steal strength when used on Creeps

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#496]
Well, maybe not steal strength, but at least give strength to the caster. More with aghs.

**Comment by Draze22** [comment]
I'd recommend 1-2 strength gain without aghs and 2-5 strength gain with aghs until we know exactly how strong it is (gain from creeps and leave steal from heroes the same).

**Comment by fcalife** [comment]
Starting this one

**Comment by fcalife** [comment]
![dota2_Xdt43vdDrF](https://user-images.githubusercontent.com/7921728/99751386-db85d280-2ac0-11eb-897b-e2004be06b73.jpg)
Implemented in https://github.com/dota2unofficial/custom_hero_clash/pull/599
