### ISSUE TITLE
Spirit bear is attackable if summoned in fountain after it dies in a duel

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#499]
This has been reported by a large number of players all describing pretty much the exact same events leading up to this.

I can confirm this from my own testing and add that as long as spirit bear is summoned in the following creep round instead or makes it to the creep round before dying it won't be attackable.

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by fcalife** [comment]
What commit fixed this?
