### ISSUE TITLE
Allow easy method to consume items when full inventory 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#504]
Two methods should be implemented. Holding down a button when buying consumesables that uses it straight away, e.g. holding down shift while buying book of paragon or strength tome will use it straight away instead of it going to backpack.

Another method is allowing players to click and consume items straight from their backpack.

**Comment by fcalife** [comment]
Implemented in https://github.com/dota2unofficial/custom_hero_clash/commit/18c1a3e4b034146f9a0c47347bfebe116efd17b4
