### ISSUE TITLE
Spirit bear sometimes can't be resummoned

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#507]
Possibly related to Issue #499.

https://www.youtube.com/watch?v=iBLjhzRnwX4

![image](https://user-images.githubusercontent.com/63279022/99867631-2d3c7300-2c0f-11eb-8063-6f768937d766.png)

![image](https://user-images.githubusercontent.com/63279022/99867640-39283500-2c0f-11eb-8856-5a127752570a.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by fcalife** [comment]
Presumably fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/3b0a970e957ea6659bc22a26b4d32128fd995e4b
