### ISSUE TITLE
Gambler

### ISSUE THREAD

**Issue by Moonscarlet** [dota2unofficial/custom_hero_clash_issues#516]
Hey,
Gambler doesn't work almost at all, I tried it in 2 games and I can't use all my gold to bet on duels, works randomly once or twice then doesn't allow me, I haven't calculated the extra % earned so I don't know about that part.
Maybe because I delay choosing the innate? I don't know.

**Comment by Draze22** [comment]
This comment is being added to the other gambler bug report.
