### ISSUE TITLE
Death ward being multicast made it last forever

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#518]
My guess is this was caused by something like a death ward multicast triggering after the duel ended because the first death ward (or first few) killed their opponent so quickly.

![image](https://user-images.githubusercontent.com/63279022/99921439-80810380-2d7e-11eb-9411-06fa57c03d41.png)

**Comment by fcalife** [comment]
Couldn't reproduce before, but this is now irrelevant because Death Ward can no longer be multicast (#580)
