### ISSUE TITLE
Aeon disk sometimes kills the player immediately

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#519]
![image](https://user-images.githubusercontent.com/63279022/99954392-c36ec580-2dd6-11eb-8d09-e99f79c5e267.png)
![image](https://user-images.githubusercontent.com/63279022/99954264-94585400-2dd6-11eb-88cd-6db24a372874.png)

**Comment by fcalife** [comment]
I was unable to reproduce this in tools; maybe triggering it involves healing, damage return, or some other itneraction I'm unaware of. It does seem to be related to overflowing integeres somehow.

Anyway, I reduced the involved damage multipliers and applied a generic fix (https://github.com/dota2unofficial/custom_hero_clash/pull/607) that should've been in place the first time anyway. I assume it will prevent this from happening, but if we get reports of it again, I'll do a more thorough investigation.
