### ISSUE TITLE
Dark Willow +32 Talent does not improve FrostHaven Bedlam

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#525]
It should.

**Comment by fcalife** [comment]
Options here are remaking Bedlam, or changing the talent to something else (non-useless).

Considering Bedlam's above average complexity and interaction with Terrorize, I'd recommend just changing the talent.

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/8c30129fba7c510477e96b68ed25298681597cec
