### ISSUE TITLE
Graffiti bugged 

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#538]
![image](https://user-images.githubusercontent.com/63279022/100490652-fa473180-3170-11eb-9269-fef8a727f9cb.png)
![image](https://user-images.githubusercontent.com/63279022/100490654-fca98b80-3170-11eb-8cc1-6d85b5123dba.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/0cIZENXH) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by fcalife** [comment]
what's a guild spray?

**Comment by Draze22** [comment]
@fcalife It's the spray that every player in a guild has.
