### ISSUE TITLE
Sentry wards placed in base can be attacked

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#543]
Would be nice to be able to place a sentry in base to see invis players items/skills without someone with truesight killing your sentry.

**Comment by fcalife** [comment]
Would true sight for everyone in the fountain be an acceptable substitute?

**Comment by fcalife** [comment]
Heroes and permanent summons are now always visible in the fountain area https://github.com/dota2unofficial/custom_hero_clash/commit/02aa9909d2d6f89a680106700ed8fb33afc3a012

**Comment by Draze22** [comment]
Perfect.
