### ISSUE TITLE
Optimise clinkz' abilities

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#545]
- Make searing arrows (frosthaven) proc from burning army skeletons
- Make skeleton walk (frosthaven) procs clinkz' level 10 talent
![image](https://user-images.githubusercontent.com/63279022/100599946-c75d9300-3354-11eb-99c7-e25291233932.png)

**Comment by fcalife** [comment]
Burning Army skeletons now use frosthaven burning arrows: https://github.com/dota2unofficial/custom_hero_clash/commit/7e8bb51a6643ed535af6a3192bec346a07ea0022

Skeleton Walk skeleton: managed to spawn the skeleton with the frosthaven ability when having the appropriate talent, but it is scuffed and has (apparently unchangeable) 1 damage, meaning its useless. Replaced the talent with a generic one instead (https://github.com/dota2unofficial/custom_hero_clash/commit/b77203f149ab3701e5105c4826dfe9d6fe8d39c9). Recommend remaking the ability if this is ever to be properly re-added.
