### ISSUE TITLE
Make winner and momentum retroactive

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#547]
Be careful when making momentum retroactive.

**Comment by fcalife** [comment]
Made Winner retroactive in https://github.com/dota2unofficial/custom_hero_clash/commit/996592e1642f6e458e0d164a5a640d10c0b6e782

I don't agree with making Momentum retroactive - I think it goes against the ability's spirit of big risk, big reward, if you can just select it after already having won 2-4 duels or so.

**Comment by Draze22** [comment]
Sounds fair.
