### ISSUE TITLE
Change the pause vote to be to enable pauses

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#549]

**Comment by fcalife** [comment]
Looking at the current code it looks like voting for this option does nothing related to pausing, but rather has to do with the in-game slowdown that we get at the beginning of overthrow. @Sheodar can you confirm?

**Comment by fcalife** [comment]
Added in https://github.com/dota2unofficial/custom_hero_clash/commit/6b5a0dc49743f2e6c0ba2e62fe4902a324321b9d
