### ISSUE TITLE
Mana shield buff remains after it's retrained

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#551]
![image](https://user-images.githubusercontent.com/63279022/100734622-0f97b680-3424-11eb-8e20-2b52b5512ada.png)

**Comment by fcalife** [comment]
As shown here, this isn't so straightforward to replicate: https://cdn.discordapp.com/attachments/682631693172998165/787932152754208778/tt7zLO89lV.gif

My guess is that this behavior is related to another bug entirely (on the hero builder), and caused passive modifiers to not be cleaned in this specific instance. This supposed new bug could trigger on another passive skill, and it happening to mana shield was just a coincidence.
