### ISSUE TITLE
Trapped creeps won't change targets

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#553]
Creeps trapped by mass serpent wards that are targeting your hero but can't get to you to attack you won't switch targets to the serpent wards.

**Comment by fcalife** [comment]
During overtime, creeps gain bonus attack range, countering this issue somewhat.

Also, its probably hard/impossible to trap all creeps in any wave with more than a few (3-4?) of them.

Due to both above considerations, i'd argue this doesn't need to be fixed.

**Comment by Draze22** [comment]
Fair enough, I only really managed to do it on single unit waves.
