### ISSUE TITLE
Decay agh's doesn't show creep value on any tooltip before buying

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#556]
![](https://cdn.discordapp.com/attachments/694440472273354762/783936655673393172/unknown.png)
![](https://cdn.discordapp.com/attachments/694440472273354762/783936682726391818/unknown.png)
![](https://cdn.discordapp.com/attachments/694440472273354762/783939130110377995/unknown.png)

**Comment by fcalife** [comment]
Fixed on https://github.com/dota2unofficial/custom_hero_clash/commit/f4e81fed8476e63a392ec92d2bf85663a32f50c9
