### ISSUE TITLE
Twins were attacking faster than they should have

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#559]
The creeps had a 7.5 attack time but are attacking roughly once every 2 seconds. This only happened on the twins round and may simply be a standard Dota mechanic or bug.

**Comment by fcalife** [comment]
I honestly can't tell what could ever cause this. The twins' ability has nothing to do with attack speed, and they behave exactly the same as any other creep.

Considering we have visual bugs like +36273421089389012 attack range arctic burn and missing talents, I'm gonna lean towards this being either a visual bug, or a misreport. And if I didn't, I would sincerely not even know where to *start* fixing it anyway.
