### ISSUE TITLE
Spamming ghost scepter at the start of a duel makes it not work but go on cooldown

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#560]
If a player spams ghost scepter during the 3 seconds of preparation time at the start of a duel it doesn't apply the ethereal effect but still goes on cooldown. 

This is only really relevant against ranged opponents who can instantly attack since casting ghost scepter immediately can be the difference between winning or losing. 

This also doesn't happen with ethereal blade.

**Comment by fcalife** [comment]
Should be fixed with https://github.com/dota2unofficial/custom_hero_clash/commit/745aeb6e5d147d99ae84626b17739fe01dd7cfbf
