### ISSUE TITLE
Add Hint about being about to shift purchase consumables

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#564]

**Comment by Draze22** [comment]
Added a loading tip for this in the next update.

**Comment by darklordabc** [comment]
Icon is not working

**Comment by fcalife** [comment]
Improved and fixed icon on https://github.com/dota2unofficial/custom_hero_clash/commit/0459b6635710f817bcf31f2816e676367a0fd877
