### ISSUE TITLE
Getting 2 earth spirit spell gives unlimited stones

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#565]
![image](https://user-images.githubusercontent.com/63279022/101236293-3146b580-3724-11eb-8cc8-16bca77799fb.png)

**Comment by fcalife** [comment]
I'm sure this bug *exists*, but there seems to be some additional condition, as I was unable to reproduce it in tools.

Added stone caller to the fountain banlist for now. This is not foolproof, as it can still be spammed on your own arena or the pvp one, but I'll consider it an improvement at least.
