### ISSUE TITLE
Players didn't get sent to creep arena

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#568]
![image](https://user-images.githubusercontent.com/63279022/101294503-d0c29000-386b-11eb-9796-e83fbca462d2.png)
![image](https://user-images.githubusercontent.com/63279022/101294509-d28c5380-386b-11eb-9f12-4ad23e9c12b2.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ogi1NAQe) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
And the round never ended as a result.

**Comment by SanctusAnimus** [comment]
No more reports or reproduction
