### ISSUE TITLE
Demo Map Issues

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#569]
- [ ] Going to a round, should kill the current round creeps and go to the one selected. 

- [ ] The shop doesnt have any of the new items
![image](https://user-images.githubusercontent.com/16277198/101315505-c8d80f80-38ae-11eb-9d0b-4d29adf225f3.png)

- [ ] What order is this in? It should be based on tier + alphabetical. Tier = 1, 2, 3, it's the creep level, it's in normal_rounds.kv If you are confused about tiers ask in discord
![image](https://user-images.githubusercontent.com/16277198/101315631-09d02400-38af-11eb-9a91-807c90ff1a14.png)

- [ ] Display Errors
![image](https://user-images.githubusercontent.com/16277198/101315838-777c5000-38af-11eb-8b16-964e01a6698b.png)
![image](https://user-images.githubusercontent.com/16277198/101315984-bca08200-38af-11eb-9dca-954bc9c11e78.png)

- [ ] Add Time Controls to menu, should show current time 1.0, and a + and - icon to increase or decrease time by .25 each click.

- [ ] I got this error at one point
```
scripts\vscripts\utils\table.lua:119: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	scripts\vscripts\utils\table.lua:119: in function 'make_key_table'
	scripts\vscripts\utils\table.lua:93: in function 'random_some'
	scripts\vscripts\game\item_loot.lua:53: in function 'ShowBossRewards'
	scripts\vscripts\game\spawner.lua:398: in function 'Finish'
	scripts\vscripts\game\spawner.lua:290: in function <scripts\vscripts\game\spawner.lua:272>
Script Runtime Error: scripts\vscripts\utils\table.lua:119: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	scripts\vscripts\utils\table.lua:119: in function 'make_key_table'
	scripts\vscripts\utils\table.lua:93: in function 'random_some'
	scripts\vscripts\game\item_loot.lua:53: in function 'ShowBossRewards'
	scripts\vscripts\game\spawner.lua:398: in function 'Finish'
	scripts\vscripts\game\spawner.lua:290: in function <scripts\vscripts\game\spawner.lua:272>
```

**Comment by HappyFeedFriends** [comment]
- [ ] The shop doesnt have any of the new items
- [ ] Add Time Controls to menu, should show current time 1.0, and a + and - icon to increase or decrease time by .25 each click.
- [ ] What order is this in? It should be based on tier + alphabetical. Tier = 1, 2, 3, it's the creep level, it's in normal_rounds.kv If you are confused about tiers ask in discord
- [ ] Display Errors
- [ ]  I got this error at one point
- [ ] Going to a round, should kill the current round creeps and go to the one selected.
