### ISSUE TITLE
Make gale impact summons 2 plague wards work on creeps

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#570]
Could maybe make it so it only summons 1 plague ward so it's not too strong or laggy.

**Comment by AustraliaIsMyCity** [comment]
this will be too laggy no matter what

**Comment by AustraliaIsMyCity** [comment]
feel free to open again if you have an idea to make it not laggy, summoning 1 ward per unit hit is too much.

**Comment by Draze22** [comment]
What if we just made it proc on ancient creeps/bosses?

**Comment by AustraliaIsMyCity** [comment]
possibly still too laggy plus kinda pointless
