### ISSUE TITLE
Player lost all abilities

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#572]
![image](https://user-images.githubusercontent.com/63279022/101482893-7c262e80-39ab-11eb-9f2e-5eff1e8f09e7.png)
![image](https://user-images.githubusercontent.com/63279022/101482917-847e6980-39ab-11eb-98e9-b742c8d3fc60.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Q0N6yoI4) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
Looks like something shitty server could do, no more reports = closing
