### ISSUE TITLE
Diretide bats kill effect can crash the server

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#573]
![image](https://user-images.githubusercontent.com/63279022/101483175-e4751000-39ab-11eb-924f-210a7bd6e078.png)
![image](https://user-images.githubusercontent.com/63279022/101483191-e9d25a80-39ab-11eb-90c0-0a3e65c5e6f5.png)

**Comment by fcalife** [comment]
Made the effect less demanding on https://github.com/dota2unofficial/custom_hero_clash/commit/a20e6113c36a4b5322f81ce8e350edfb77fb1710 by reducing particle emission count. Should help on slower computers. If that was not the reason of the crashes, they'll keep happening, so just open this again if that's the case.
