### ISSUE TITLE
Feral impulse and shapeshift not working 

### ISSUE THREAD

**Issue by HumanNugget** [dota2unofficial/custom_hero_clash_issues#575]
Also , please make two different books one containing passives and one actives

**Comment by dym-sh** [comment]
unclear why it was closed, but `Feral impulse` did not work in a game like 5 minutes ago

**Comment by Draze22** [comment]
@dym-sh Feral impulse doesn't work in the fountain, did you check during a creep round or duel?

**Comment by dym-sh** [comment]
@Draze22 not sure, but dmg numbers did not changed on the hero, iirc

**Comment by Draze22** [comment]
If you get it again check during a round and take a screenshot if it's not working.
