### ISSUE TITLE
Dead player got retraining items

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#578]
This only happens if the player dies after everyone else finishes a round that gives retraining items.

┆Issue is synchronized with this [Trello card](https://trello.com/c/uNRO3omZ) by [Unito](https://www.unito.io/learn-more)

**Comment by 56kyle** [comment]
I remember this happening before, but after testing this in tools mode quite a bit and eventually in a normal match it doesn't seem to occur anymore
