### ISSUE TITLE
Consider removing rolling boulder and frost armor from jabberwock

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#585]
![image](https://user-images.githubusercontent.com/63279022/101968273-6eee9580-3c72-11eb-813c-3a8ff8560d3b.png)

**Comment by fcalife** [comment]
Implemented in https://github.com/dota2unofficial/custom_hero_clash/commit/93262178b70dab4924de1a5b8596809a1b34db76
