### ISSUE TITLE
Scepter extra abilities mess up ability hotkeys

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#589]
Some abilities no longer have a hotkey, and clicking the hotkey that would normally correspond to the ability's position on the hotbar results in a 'not learned' message.

![zIj1mHA8IL](https://user-images.githubusercontent.com/7921728/102050963-89d01f80-3dc2-11eb-892b-1dae682c4fd6.gif)

Presumed to be related to scepter abilities since it fixes itself after you unlearn them (not shown in the gif, but would mean it fixes itself when you unlearn strafe), but could be a coincidence. It's annoying either way.

┆Issue is synchronized with this [Trello card](https://trello.com/c/rIqrberx) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
I think it's related to players only being given a number of hotkeys equal to the number of abilities they've learned. The same thing happens with multi part abilities such as attribute shift.

**Comment by Draze22** [comment]
So this is fixed now?

**Comment by Draze22** [comment]
Pretty sure this is fixed now.
