### ISSUE TITLE
Ability rework megathread

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#593]
A megathread for reworks to abilities so I can go through them when I get bored

**Comment by AustraliaIsMyCity** [comment]
- [ ] Remove 50% reduction on sleight of fist

**Comment by fcalife** [comment]
Done in https://github.com/dota2unofficial/custom_hero_clash/commit/be831e6955b4d7f609f09c327798d2930f480cff

**Comment by HumanNugget** [comment]
tinkers laser doesnt jump between creeps with agh upgrade

**Comment by fcalife** [comment]
No longer relevant
