### ISSUE TITLE
Abandoned player won the game

### ISSUE THREAD

**Issue by vlamorsky** [dota2unofficial/custom_hero_clash_issues#596]
![2020-12-17_04-36](https://user-images.githubusercontent.com/58402372/102427227-f8f77f00-4021-11eb-81fd-4c0ca6b57576.png)

The game says that I finished second. But there was a player who did not load. He probably won (it's scary). But the standard match statistics say the opposite (gave me the winner's mark (the star)).

It is possible that this is just a visual bug. But the game continued after my death. However, not for long.

![222](https://user-images.githubusercontent.com/58402372/102427595-b6827200-4022-11eb-93dd-04919d44050d.png)

**Comment by Draze22** [comment]
Duplicate report.
