### ISSUE TITLE
Make finger of death damage per kill work on creeps

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#601]
No need to reduce the damage per kill against creeps as this won't be particularly powerful.

**Comment by Snoresville** [comment]
I'm sure that the ability will now scale with creep kills from the finger, I'll close this.

**Comment by AustraliaIsMyCity** [comment]
how much damage does it gain?

**Comment by Snoresville** [comment]
Draze thinks that the damage shouldn't be reduced
40 damage per kill, +20 with lion finger

**Comment by AustraliaIsMyCity** [comment]
if its per unit killed then make it 6+3

**Comment by fcalife** [comment]
Implemented on https://github.com/dota2unofficial/custom_hero_clash/pull/634
