### ISSUE TITLE
Holy persuasion can be cast on creeps

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#604]
Holy persuasion is somehow an ability in the game again.

**Comment by AustraliaIsMyCity** [comment]
"chen" {
  "1"    "chen_penitence"
  "2"    "chen_divine_favor"
  "3"    "chen_test_of_faith"
  "4"    "chen_hand_of_god_lua"
  }
 This has been the same for a while, are you sure holy persuasion was in the game? (perhaps someone used cheats mode?)

**Comment by fcalife** [comment]
Couldn't find the ability in the game. I suspect this is confusion related to HoD 2.
