### ISSUE TITLE
Abilities with charges seem to be broken

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#605]
![image](https://user-images.githubusercontent.com/63279022/102578561-89cb7900-414e-11eb-96b7-7643e7b2d47a.png)

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/102583255-77eed380-4158-11eb-8214-56e1e5091045.png)

**Comment by fcalife** [comment]
Should be fixed now
