### ISSUE TITLE
Key assignment issue

### ISSUE THREAD

**Issue by GGoker** [dota2unofficial/custom_hero_clash_issues#607]
Hi, After new update to Dota, we lost assignments to skills. In order to use skills we need to click on it with mouse. Please fix this bug asap. screenshot is attached. Thanks

**Comment by GGoker** [comment]
![WhatsApp Image 2020-12-18 at 23 41 22](https://user-images.githubusercontent.com/76230365/102665014-0ed98100-4195-11eb-8662-4dd60d64c62c.jpeg)

**Comment by desura72** [comment]
Issue still is not fixed. Please find a solution! Thank you :)

**Comment by Draze22** [comment]
We have a solution, we just need Valve to allow us to fix it.
