### ISSUE TITLE
[7.28] Update any overriden talents to match new values

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#626]
Go through the 7.28 patch notes and check every changed talent. If we are overriding it for some reason, make sure its type and value matches the new one.

Also make sure to re-add any talents which are no longer useless, if that applies to any of them.

**Comment by Draze22** [comment]
I did this with any I noticed while reading through the patch notes but there could be more.

**Comment by Draze22** [comment]
All of these should be done now.
