### ISSUE TITLE
[7.28] Update list and source of scepter abilities

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#629]
Also remember to update all relevant tooltips on both source and granted abilities.

- [x] Add: Blink fragment (should be tied to Blink)
- [x] Remove: Rune Forge. ~~Add it to the regular ability pool.~~
- [x] Change: Sproink (tie it to Impetus instead of Untouchable, since it now throws Impetus attacks).
- [x] Add: Will o' Wisp. Tie it to Chakra Magic.
- [x] Add: Nihilism. Tied it to Pulse Nova.
- [x] Add: Dig. Tie it to Ransack.

**Comment by SanctusAnimus** [comment]
Do we really need Rune Forge as a standalone ability?

**Comment by fcalife** [comment]
Updated

**Comment by fcalife** [comment]
FInished in https://github.com/dota2unofficial/custom_hero_clash/commit/0063361005fba25ada226b687f3a61587df7c693 and https://github.com/dota2unofficial/custom_hero_clash/commit/12b4d75c3e03f7784d783e6850f1449f9da9f5b0
