### ISSUE TITLE
Dark portrait can be retrained 

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#632]
![image](https://user-images.githubusercontent.com/63279022/102705230-35a0d000-42d9-11eb-94c4-a0fb8bfa2aae.png)
![image](https://user-images.githubusercontent.com/63279022/102705233-38032a00-42d9-11eb-8ae3-69a295838952.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch
