### ISSUE TITLE
Consuming blessing after losing ability to choose innate didn't give aghs effects

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#633]
![image](https://user-images.githubusercontent.com/63279022/102705247-697bf580-42d9-11eb-8344-80b9497da438.png)
![image](https://user-images.githubusercontent.com/63279022/102705248-6ed94000-42d9-11eb-9b0a-574c0083e4a7.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch

**Comment by fcalife** [comment]
What commit fixed this?

**Comment by HappyFeedFriends** [comment]
I forgot to send a commit. Already did.

**Comment by fcalife** [comment]
I don't understand how this fix relates to the issue at hand, but I'm sure it fixes *something*. closed.
