### ISSUE TITLE
Fix Fire Spirits (and potentially other abilities)' shard behavior

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#639]
The behavior on the ability is as follows:

* learn it without shard: works normally (non-shard behavior)
* buy shard after it is learned: does not work
* buy shard, then learn it: works normally (shard behavior)

There's probably a few abilities which behave like this. Need to make a list and have it so when a shard is purchased, they are unlearned/learned again in order to clean those behaviors.

┆Issue is synchronized with this [Trello card](https://trello.com/c/HIyjCPWE) by [Unito](https://www.unito.io/learn-more)

**Comment by Snoresville** [comment]
Related branch has been merged
