### ISSUE TITLE
Ability notes are broken

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#640]
All of them are blank atm

![image](https://user-images.githubusercontent.com/7921728/102972714-41a7b000-44da-11eb-9be4-f92938b70bac.png)

**Comment by GGWP23121** [comment]
Во время использования ультимейта с мультикастом, кастомка вылетает и нельзя войти, почините пожалуйста 
![image](https://user-images.githubusercontent.com/76522648/102997898-2b7c0d00-4537-11eb-9b36-182da94e1bf3.png)

**Comment by SanctusAnimus** [comment]
Ability notes will be fixed in the next patch
