### ISSUE TITLE
Phantom assassin's left level 25 talent is broken

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#645]
I checked npc_hero_custom and everything there seems fine, not sure what's causing this.

![image](https://user-images.githubusercontent.com/63279022/103123430-71bca200-46d8-11eb-8ee9-12f73e43d6f0.png)

**Comment by AustraliaIsMyCity** [comment]
Fixed https://github.com/dota2unofficial/custom_hero_clash/commit/718e7b921bf9b0408dbb1cc4e3fb47a550084192
