### ISSUE TITLE
Snapfire gobble up can turn creeps into allies

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#647]
![image](https://user-images.githubusercontent.com/63279022/103123558-dc6ddd80-46d8-11eb-85d1-4d7b83d0bb61.png)
![image](https://user-images.githubusercontent.com/63279022/103123564-ded03780-46d8-11eb-813c-a9b20c4d9bbb.png)

**Comment by HappyFeedFriends** [comment]
The ability is removed from the hero in next patch
