### ISSUE TITLE
Greater treants don't have summon power yet

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#650]
![image](https://user-images.githubusercontent.com/63279022/103123752-7a61a800-46d9-11eb-85df-950e5f971b19.png)
![image](https://user-images.githubusercontent.com/63279022/103123770-8baab480-46d9-11eb-8c1f-b08eb9e50968.png)

**Comment by AustraliaIsMyCity** [comment]
Fixed https://github.com/dota2unofficial/custom_hero_clash/commit/a128729afbcf4ff3f770eefb85881b2c2cd7115f
