### ISSUE TITLE
Kaya upgrades redesign

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#652]
With 7.28 and the changes to octarine core, many players have been complaining about the lack of a spell lifesteal item with spending an inventory slot on, plus for a long time I've felt the game needs a more expensive/powerful magic resistance item. Also the kaya 2 and 3 code is complete garbage holy shit. So here's my idea:

Kaya [2050] + Mystic Staff [2800] + Recipe [500] = Sky Staff [5350]
+ 45 Intelligence
+ 30% Mana Regen Amplification
+ 30% Spell Lifesteal Amplification
+ Passive: Arcane Proficiency
Provides +0.6% Spell Amplification per point of intelligence (reduced to 0.15% in duels).
[Notes] Does not stack with any unique spell amplification items or itself.

Sky Staff [5350] + Eternal Shroud [3250] + Recipe [1650] = Starforce [10250]
+ 55 Intelligence
+ 40% Mana Regen Amplification
+ 40% Spell Lifesteal Amplification
+ 30% Magic Resistance
+ 10 HP Regeneration
+ 30% Spell Lifesteal (Heroes)
+ 15% Spell Lifesteal (Creeps)
+ Active: Divine Restitution [50 MP] [60 CD]
Creates a spell shield on an ally that absorbs up to 600 magical damage, converting damage taken into mana. Lasts 12 seconds. 
[Notes] Cannot be multicast. Can be self cast.
+ Passive: Arcane Mastery
Provides +1.2% Spell Amplification per point of intelligence (reduced to 0.3% in duels).
[Notes] Does not stack with any unique spell amplification items or itself.

edit: modified some values
edit 2: added some notes

**Comment by Draze22** [comment]
Seems like an overall buff to mages compared to before 7.28 which seems fine, they're generally less reliable and more difficult to play in FFA and shouldn't unbalance the DUOS meta (where mages are much stronger) significantly.

**Comment by fcalife** [comment]
Looks good to me, dont call my code trash you whelp :D

**Comment by AustraliaIsMyCity** [comment]
> Looks good to me, dont call my code trash you whelp :D

nah iirc its code from chaos

**Comment by AustraliaIsMyCity** [comment]
https://github.com/dota2unofficial/custom_hero_clash/pull/620 done
