### ISSUE TITLE
Sharpshooter crashes the game if multicast

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#654]
![image](https://user-images.githubusercontent.com/63279022/103143709-2bb31d00-4770-11eb-8a9d-703f43b47992.png)

**Comment by AustraliaIsMyCity** [comment]
Fixed
https://github.com/dota2unofficial/custom_hero_clash/commit/134f2626275b82c4c2ec78c5bbd17bb57c0d8ea4
