### ISSUE TITLE
Minor UI bugs

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#657]
Neutral items are faded/darker.
![image](https://user-images.githubusercontent.com/63279022/103145317-78a4ec80-478c-11eb-9de0-94707b1f5853.png)

Duel wins/losses are faded/darker.
![image](https://user-images.githubusercontent.com/63279022/103145322-8fe3da00-478c-11eb-829e-b72a19676682.png)

Round timer is faded.
![image](https://user-images.githubusercontent.com/63279022/103145331-aab64e80-478c-11eb-9dfa-4318af37787e.png)

**Comment by HappyFeedFriends** [comment]
Valve bug related to rendering. closed

**Comment by fcalife** [comment]
(its related to the bug where some people's inventory slots are just black boxes)
