### ISSUE TITLE
Make nimbus tied to lightning bolt instead of thundergods wrath

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#667]
That way we can remove thundergods wrath from the game since thundergods vengeance is just a better version of it.

**Comment by Snoresville** [comment]
a tweak has been checked and merged, closing

**Comment by Draze22** [comment]
Removed Thundergod's Wrath: https://github.com/dota2unofficial/custom_hero_clash/commit/a4a8ca78974a0b9818df16a7f4cc1297a97f038b.
