### ISSUE TITLE
Fire spirits (with shard) can't be rerolled

### ISSUE THREAD

**Issue by kdrturhn** [dota2unofficial/custom_hero_clash_issues#671]
![6skillbug](https://user-images.githubusercontent.com/76650330/103170669-09e09580-4857-11eb-999f-3649489d67da.png)

I was randomly rerolling a skill then came across "Launch the Spirit" skill, as it shows I have 6 skills right now but can only reroll 5 of them, the skill does not indicate it cannot be rerolled so I thought it must be a bug. FYI.
Best Regards,
A fellow CHC lover.

┆Issue is synchronized with this [Trello card](https://trello.com/c/YFtCEb4A) by [Unito](https://www.unito.io/learn-more)

**Comment by darklordabc** [comment]
Fixed in other issue.
