### ISSUE TITLE
Make items in the stash get refreshed after a duel

### ISSUE THREAD

**Issue by dym-sh** [dota2unofficial/custom_hero_clash_issues#673]
not sure if its intended, but same items in backpack do get refreshed after duel

something like midas or necro-2x are most likely to suffer from this

**Comment by Draze22** [comment]
I'll make a poll and see what players think.

**Comment by Draze22** [comment]
![Uploading image.png…]()

**Comment by fcalife** [comment]
Added in https://github.com/dota2unofficial/custom_hero_clash/commit/bceaff4f386a476eb2fd7aaa79440f360e5d46dd
