### ISSUE TITLE
God's Rebuke still shows it gets a lowered cooldown by aghs scepter

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#674]
God's Rebuke no longer has an aghs effect as of 7.28.

![image](https://user-images.githubusercontent.com/63279022/103183309-9ea1cc80-4905-11eb-901d-1cf67aa9c6c1.png)

**Comment by Snoresville** [comment]
seems to happen in normal dota as well

**Comment by Draze22** [comment]
@Snoresville if that's the case you can go ahead and close this issue.

**Comment by Snoresville** [comment]
unfortunately, i dont have the privilege of closing issues, so i'll just say that we will wait until valve deletes the leftover text

**Comment by darklordabc** [comment]
So wait, it doesnt get lowered cooldown and its meant to?

**Comment by Snoresville** [comment]
No, God's Rebuke scepter has been replaced with bulwark scepter. The cool down reduction won't work now.

**Comment by Draze22** [comment]
But Valve screwed up and haven't changed the tooltip text.
