### ISSUE TITLE
Demo Map Issues

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#681]
- [x] **Select round forces you to vs same creeps forever** - "Select Round" forces you to keep versing that same creep round forever
Basically once you use it once, you cannot return to normal
Not sure its a bug, but its a problem
Even if you use "Go to Round" after "Select Round", it will forever be vsing the last creeps you choose to vs

- [x] **Add Sounds to buttons** - Add interesting sounds to the buttons, currently nearly all of the buttons have no sounds connected to them.

- [x] **Time Scale needs better interface** - There is no good way to increment this, its impossible to return it to 1.00 because of how the dragging works. It needs a reset button, and a 2 or 4 buttons for players to press to move it along scale in predictable fashion, drag, and move is bad for this. 
![image](https://user-images.githubusercontent.com/16277198/103187264-d1ed5700-4917-11eb-985f-9eca4d11a9f0.png)

- [x] **Why are these buttons?**
![image](https://user-images.githubusercontent.com/16277198/103187327-0e20b780-4918-11eb-9b50-95e5b581f5f1.png)
![image](https://user-images.githubusercontent.com/16277198/103187333-124cd500-4918-11eb-8d24-01abf1df783d.png)

- [x] **Just have it be "LVL" and remove the ":"**
![image](https://user-images.githubusercontent.com/16277198/103187351-2395e180-4918-11eb-8c61-89679c626ff8.png)

- [x] **Add Select Mastery Button** - Needs a select Mastery Button. The select mastery button should be able to pick ANY mastery but also ANY level of ANY mastery.
![image](https://user-images.githubusercontent.com/16277198/103187370-3a3c3880-4918-11eb-9830-8cf75e076e23.png)

- [x] **Boss Button does not behave correctly** - "Boss" does not work very well. I press it, it goes to round 20 (for example), I press it again, it goes to round 20 again, it should go to the next boss round.

- [x] **Add Aegis is missing UI effect and doesn't seem to work** - "Boss" does not work very well. I press it, it goes to round 20 (for example), I press it again, it goes to round 20 again, it should go to the next boss round. This should change to [aegis icon] x 4 or whatever
![image](https://user-images.githubusercontent.com/16277198/103187425-5f30ab80-4918-11eb-9423-0e523257d8d7.png)

**Comment by Snoresville** [comment]
- [ ] Demo ability selection list needs to be re-ordered to match the order seen on heroes in normal Dota
![image](https://user-images.githubusercontent.com/19840964/104079037-f24ed700-5270-11eb-9df1-4f6e22d4490a.png)

**Comment by fcalife** [comment]
Close this and let @Snoresville and @ZLOY5 claim it

**Comment by Snoresville** [comment]
alright
