### ISSUE TITLE
Update Patreon to reflect all the benefits (Fortune and Masteries are missing)

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#683]
![image](https://user-images.githubusercontent.com/16277198/103188799-ff3d0380-491d-11eb-9742-bd0bbb855ab6.png)

**Comment by AustraliaIsMyCity** [comment]
![image](https://user-images.githubusercontent.com/50186248/103188884-58a53280-491e-11eb-9b91-2ce0d2f6b030.png)
done
