### ISSUE TITLE
All dispellable effects if used during overtime sometimes bug out for the rest of the game

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#686]
Players have reported ghost scepter, decrepify, windrun, guardian angel and empower all getting dispelled almost instantly after use for the entire game after they used that ability/item during overtime.

**Comment by dym-sh** [comment]
related: if `Doom`ed player didnt die during duel, Doom persist for the full duration in the fountain

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/103252229-ff95d700-49cf-11eb-8ab2-45926c164da9.png)

**Comment by AustraliaIsMyCity** [comment]
possibly fixed, waiting to see https://github.com/dota2unofficial/custom_hero_clash/commit/7ea4bfda8bc05d293e235351cfad2a6ad531aa58

**Comment by AustraliaIsMyCity** [comment]
fixed
