### ISSUE TITLE
Abilities that become self castable when upgraded by aghs shard sometimes don't work

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#687]
When I tested it I had no trouble casting frostbite on myself but wasn't able to cast demonic purge on myself.

![image](https://user-images.githubusercontent.com/63279022/103205605-0845c900-494e-11eb-89d8-d773c68d6381.png)

**Comment by SanctusAnimus** [comment]
cause demonic purge is custom and is not updated for 7.28+
