### ISSUE TITLE
Linken's sphere/pendant, mirror shield and lotus disk can be popped by some items and abilities while still in fountain

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#689]
![image](https://user-images.githubusercontent.com/63279022/103272063-fb89a980-4a0f-11eb-8cd7-c660fd95a7fd.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/WrvGKdAD) by [Unito](https://www.unito.io/learn-more)

**Comment by Snoresville** [comment]
is it important that those items/spells have to target invulnerable units?

**Comment by Draze22** [comment]
It's important that some of these can target invulnerable allies but none of them should be able to target enemies.

**Comment by ZLOY5** [comment]
Good enough just forbid cast abilities to enemies during preparation phase?

**Comment by Draze22** [comment]
Players are already invulnerable during during the preparation phase, some abilities can just pierce this invulnerability.

**Comment by Snoresville** [comment]
one solution is to refresh the cooldowns of said items before duels, would that sound fair? i am imagining that it would open up like a "double linkens" strat in duos (can't be done in solos) where the pair would cast linkens on each other and can potentially block two spells

**Comment by Draze22** [comment]
Sounds like a bad solution.

**Comment by Snoresville** [comment]
Woah, at least consider and make an argument on why, 30 seconds between duels is long enough to refresh the cooldowns of sphere/pendant/mirror shield/lotus disk.

**Comment by Draze22** [comment]
You already brought up a good reason not to since you can pre-cast them before duels and have them refreshed when the duel starts for an extra use which works in FFA too since you can cast them on yourself.

**Comment by Snoresville** [comment]
Oh, fair enough. We can just purge it before duels.
![image](https://user-images.githubusercontent.com/19840964/107110164-9e4a0900-6895-11eb-881a-9dcaa506cef1.png)
Dota Wiki says you can't use Linkens on yourself. I tested in game and it confirms that information.

**Comment by ZLOY5** [comment]
> Players are already invulnerable during during the preparation phase, some abilities can just pierce this invulnerability.
Yes. but i speak about preventing cast, so they completely cant cast target abilities on enemies during preparation

**Comment by Draze22** [comment]
That should work.
