### ISSUE TITLE
Change how split shot and searing arrows frosthaven can't be rolled with marksmanship

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#694]
Currently split shot and searing arrows frosthaven can't be obtained when the player has marksmanship and vice versa.

We should change it so that only Medusa can't get both split shot and marksmanship and only Clinkz can't get both searing arrows frosthaven and marksmanship since those are the only situations that require these combos to be restricted.

We also need to make sure they can't trade in duos to get these banned combos.

┆Issue is synchronized with this [Trello card](https://trello.com/c/6U1waqNu) by [Unito](https://www.unito.io/learn-more)

**Comment by Snoresville** [comment]
oke it's done
