### ISSUE TITLE
Add an upgrade for gem of truesight that consumes it

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#705]
The effects of the upgrade would be identical to gem of truesight except that it doesn't get dropped on death.

The polls indicate most players want this addition and that the recipe should cost from 7k-10k gold.

![image](https://user-images.githubusercontent.com/63279022/103591910-99680180-4f45-11eb-9b26-189157a5f0e0.png)

**Comment by AustraliaIsMyCity** [comment]
no

**Comment by AustraliaIsMyCity** [comment]
did you fucking edit the poll too wtf

**Comment by AustraliaIsMyCity** [comment]
you cant do that

**Comment by Draze22** [comment]
I didn't edit the poll, it's just outdated

**Comment by Draze22** [comment]
wait what do you mean by edit the poll?

**Comment by Draze22** [comment]
When I edited the poll at most 10% of people had responded and all I did was double the cost ranges so if you want to suggest reducing the cost of the recipe go for it.

**Comment by Draze22** [comment]
This was added as a purchasable neutral item this commit: https://github.com/dota2unofficial/custom_hero_clash/commit/884bb17ff3431e40e4c13a5102cba1d34d727019.
