### ISSUE TITLE
Your abilities will have their cooldowns refreshed if you disconnect and reconnect to the the game

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#706]
![image](https://user-images.githubusercontent.com/63279022/103593181-35dfd300-4f49-11eb-82f1-072cba101404.png)

**Comment by AustraliaIsMyCity** [comment]
im predicting whoever did this just happened to be in a duel while they were dc'd

**Comment by Draze22** [comment]
Agreed, I'd still like to test it out to make sure but it takes me to long to reconnect.

**Comment by fcalife** [comment]
Tested just now.

Before disconnecting: 
![rJRWpnnMgN](https://user-images.githubusercontent.com/7921728/105572646-38a73a00-5d37-11eb-9aa2-58f37774a9e4.png)

After reconnecting: 
![dota2_g4vyDVvjh8](https://user-images.githubusercontent.com/7921728/105572651-3d6bee00-5d37-11eb-8f8a-08fc7de3c959.png)
