### ISSUE TITLE
Book of shadows tooltip is wrong

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#715]
Should say it lasts for 4 seconds.

![image](https://user-images.githubusercontent.com/63279022/104079023-0d234a80-5275-11eb-80c7-01e299066f76.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/104111460-deb77500-5331-11eb-9e65-b565b7f33a69.png)
seems to happen in normal dota as well. we can wait for valve to fix the name or just fix it in our localizations

**Comment by Draze22** [comment]
It's supposed to be a 3 second duration in vanilla Dota, we buffed it to 4 seconds for CHC.

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/104113131-8474df00-5346-11eb-878b-80791e99acd4.png)
![image](https://user-images.githubusercontent.com/19840964/104113135-8c348380-5346-11eb-9689-aba4fba914f0.png)
the buff is redundant. kv and in-game both corroborate the 4 second buff

**Comment by Snoresville** [comment]
it's been merged now, let's close this
