### ISSUE TITLE
Tempest double doesn't get aghanim's shard or neutral items

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#723]
![image](https://user-images.githubusercontent.com/63279022/104119672-2adfd500-5385-11eb-87d0-2e24012c9201.png)
![image](https://user-images.githubusercontent.com/63279022/104119675-30d5b600-5385-11eb-9b26-0238ceca126e.png)

**Comment by HappyFeedFriends** [comment]
fixed in next patch https://github.com/dota2unofficial/custom_hero_clash/commit/c479173086c76b38c09a526c9f3dcc6f08d205ff
