### ISSUE TITLE
1 hp bag can't regen

### ISSUE THREAD

**Issue by mangequ** [dota2unofficial/custom_hero_clash_issues#724]
![image](https://user-images.githubusercontent.com/77242856/104130952-ac833300-5384-11eb-9c1a-c6b2bfa2908c.png)
 io and meduse 117 min 
№5780952078 match number

**Comment by Snoresville** [comment]
Can't get replays of custom games, and thus screenshot is useless. Almost considering closing this if no better evidence comes up.

**Comment by fcalife** [comment]
Duplicated
