### ISSUE TITLE
Stuck at 1 health point. Cannot regen

### ISSUE THREAD

**Issue by DFined** [dota2unofficial/custom_hero_clash_issues#727]
During round approximately 130 player hp can instantly drop to 1 (possibly connected to dark willow's shadow realm, as it always happened to me in that ability). After that health can not be regenerated in any way. Buying an Aeon disk makes the health get stuck at 70% instead, but any damage, whoever small will trigger the disk and cause the hp to go back to 1 again. The hp will then stay at 1 until the Aeon disk is refreshed or cools down, at which point it will go back to 70%.
https://user-images.githubusercontent.com/16002547/104220367-714e3600-5450-11eb-8b81-2140ef1f691f.mp4

**Comment by fcalife** [comment]
duplicate
