### ISSUE TITLE
Player got marksmanship + split shot on medusa

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#735]
![image](https://user-images.githubusercontent.com/63279022/104661757-53692580-571d-11eb-8e9b-27bc12ee1868.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Ue3ohAoT) by [Unito](https://www.unito.io/learn-more)

**Comment by 56kyle** [comment]
I tried for a little while to duplicate in duos without swapping and wasn't  able to. Still not sure as to origin but best guess is that it has to do with either swapping abilities or possibly the  timing of when the ability is removed from the list. Will look through and try to ensure that ability name entries occur before deletions later tonight

**Comment by Snoresville** [comment]
we're gonna fix this by allowing this combination in the rewritten marksmanship

**Comment by fcalife** [comment]
no longer relevant, @Snoresville claim this one
