### ISSUE TITLE
Revenge bonus aegis can't be triggered by losing a duel

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#737]
Can happen in both duos and ffa. Also in duos it also causes their team mate to not lose aegises from duels.

![image](https://user-images.githubusercontent.com/63279022/104837102-9508f480-5906-11eb-8ae9-795e11691eed.png)
![image](https://user-images.githubusercontent.com/63279022/104837128-b538b380-5906-11eb-8804-b687b1492e7e.png)

**Comment by Snoresville** [comment]
if there is no more issues brought up about this, then i believe it is fixed

**Comment by Draze22** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/compare/accf3376647f...fccab77038a9.
