### ISSUE TITLE
Order of Items in Collection is still wrong

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#740]
Boost and Gold Boost Items should always appear first in the list (in Default view)
![image](https://user-images.githubusercontent.com/16277198/104906236-8d655080-59d7-11eb-90b9-276fade0b889.png)

This issue applies to 12v12 and Overthrow

**Comment by SanctusAnimus** [comment]
It works correctly if you have server connection
![image](https://user-images.githubusercontent.com/43399078/104907260-7c8fed00-598d-11eb-9612-6c80b7353f34.png)

**Comment by Sheodar** [comment]
Collection logic don't work wihout server connection
