### ISSUE TITLE
Tree grab gives tree throw when picked

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#741]
Tree throw then has no cooldown and can be used an infinite number of times. If you use tree grab this bug gets fixed.

![image](https://user-images.githubusercontent.com/63279022/104976197-bfff5f80-5a50-11eb-9b55-65b8a8c26ee5.png)

**Comment by Snoresville** [comment]
Venomancer at level 25 (No items)

No Talent:
![plague_ward](https://user-images.githubusercontent.com/19840964/105123855-f5797b00-5b2c-11eb-9853-7764f2e8fa77.PNG)

With Talent
![plague_ward_talent](https://user-images.githubusercontent.com/19840964/105123864-f90d0200-5b2c-11eb-8926-72f77e527cd2.PNG)

Health does not change when talent is chosen. However, base damage does.
