### ISSUE TITLE
Broodmother spawn spiders health talent doesn't work

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#746]
![image](https://user-images.githubusercontent.com/63279022/105253119-ec42e980-5bd2-11eb-8438-f8bf54d37560.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Rb9QjHKh) by [Unito](https://www.unito.io/learn-more)

**Comment by Shushishtok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Broodmother spawn spiders damage talent doesn't work #746](https://trello.com/c/hw8VcxEL/217-broodmother-spawn-spiders-damage-talent-doesnt-work-746)

**Comment by Nibuja05** [comment]
Checked if that is true:
- with everything I tested it seems that the attack bonus is applied correctly
- however the bonus spider life talent on lvl 25 seems not to work

**Comment by Nibuja05** [comment]
![image](https://user-images.githubusercontent.com/45997731/106326666-24a29180-627d-11eb-85b0-08312c9d13ff.png)
Spiderites health as seen in the picture with the summon buff is 264 max. Witht the talent they should have at least 470 without the summon buff
