### ISSUE TITLE
Demo mode polishing

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#749]
- [x] Remove initial 'pick a mastery' pop-up (mastery icon can stay since it shows which one is currently selected)
- [x] This section of the UI (round info + scoreboard) should move to the right when the demo menu is open: 
![image](https://user-images.githubusercontent.com/7921728/105285436-28565a00-5b93-11eb-9f2a-40aa8772d8e6.png)

- [x] this shouldn't be a button, or clickable:
![image](https://user-images.githubusercontent.com/7921728/105285761-d06c2300-5b93-11eb-897e-0e547e044516.png)

- [x] Confirming the round number with ENTER should have the same effect as clicking the left button here:
![image](https://user-images.githubusercontent.com/7921728/105285881-04dfdf00-5b94-11eb-9cd5-5a71afb74cbb.png)

- [x] Remove this random "MISC" label 
![image](https://user-images.githubusercontent.com/7921728/105285914-175a1880-5b94-11eb-88dc-521f2242c8e7.png)

- [x] Either add a button that resets the current hero's level to 1, or make it so switching heroes doesn't keep the old hero's level
- [x] After the player 'dies' for real and the game would end, give them the option of continuing (because restarting the game is annoying)
- [x] After adding an ability from a search (excellent search functionality btw), clear the search field and reset the window's state accordingly, so the user can immediately search/add more abilities
- [x] For some reason, 'time lock' and 'time dilation' do not appear when searching for 'time':
![image](https://user-images.githubusercontent.com/7921728/105286638-766c5d00-5b95-11eb-9c60-5d13392c50c9.png)

- [x] Add a panel where we can buy any of the droppable neutral items
- [x] I'm not sure if this button should exist. There's already a 'pause' button that performs its function better. Maybe it should be a button (instead of a checkbox) and simply kill any currently alive creeps, and be labeled 'kill'. 
![dota2_O48iRu3mzb](https://user-images.githubusercontent.com/7921728/105362183-5494c980-5bd9-11eb-9d25-c9a5ace090f0.png)

- [x] Remove this and make it always on by default.
![image](https://user-images.githubusercontent.com/7921728/105292351-9c92fc80-5b97-11eb-9975-23d9020fcfb3.png)

**Comment by darklordabc** [comment]
I love this

**Comment by fcalife** [comment]
All done, feel free to close & claim the issue!
