### ISSUE TITLE
Scroll of duplicity doesn't work

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#753]
![image](https://user-images.githubusercontent.com/63279022/105467730-31a60a80-5cea-11eb-9cf6-bfee689cf212.png)
![image](https://user-images.githubusercontent.com/63279022/105467748-3965af00-5cea-11eb-9a1a-034172e205f6.png)

**Comment by Draze22** [comment]
Scroll of duplicity seems to be broken in the current patch.

**Comment by Draze22** [comment]
Apparently the second mastery is free at the moment which would explain this, either scroll of duplicity needs to be removed or masteries need to be reverted to only being able to pick 1 for free.

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/01c1bc606959e29e677aff7b2893babc2da27e67
