### ISSUE TITLE
Io talents broke

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#754]
The talents were like that from the start of the game.
![image](https://user-images.githubusercontent.com/63279022/105475021-0673e900-5cf3-11eb-9317-3c93f6c20a23.png)
![image](https://user-images.githubusercontent.com/63279022/105475042-0bd13380-5cf3-11eb-9b52-a93adca5f73e.png)

**Comment by Draze22** [comment]
Could just be that IO's talents are broken every time it is picked.

![image](https://user-images.githubusercontent.com/63279022/105560945-876dc780-5d69-11eb-9632-2473ec9d2ea4.png)
![image](https://user-images.githubusercontent.com/63279022/105560954-8d63a880-5d69-11eb-8a6b-e303a2248bee.png)

**Comment by Snoresville** [comment]
fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/6d223ac491c8160534f4c85c7c12e735d61f79ce
