### ISSUE TITLE
Third eye stops working in a duel after reincarnation is used

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#762]
![image](https://user-images.githubusercontent.com/63279022/105617608-86a16800-5e33-11eb-9938-50d2af64ddbe.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/dHg06fu9) by [Unito](https://www.unito.io/learn-more)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Third eye stops working in a duel after reincarnation is used #762](https://trello.com/c/PScrGbZv/187-third-eye-stops-working-in-a-duel-after-reincarnation-is-used-762)

**Comment by Draze22** [comment]
Third eye got removed so this is no longer relevant.
