### ISSUE TITLE
Using a skill to proc overload while it's being retrained crashes the server

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#764]
![image](https://user-images.githubusercontent.com/63279022/105617653-10513580-5e34-11eb-83de-f92ab051c5a8.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/xoYjUm3a) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
1. Retrain overload but don't pick a new skill to replace it (get part way through retraining it).
2. Use a skill to proc overload.
3. Completely retrain overload.
4. Attack a unit and when the attack lands the server will crash.

**Comment by darklordabc** [comment]
This is indeed a serious problem, but I'm not sure why my input is required?

**Comment by Draze22** [comment]
It's not, it just wouldn't let me move it to needs to be assigned 
![image](https://user-images.githubusercontent.com/63279022/106735665-a3764080-6668-11eb-8da4-7765553b01a4.png)

**Comment by AustraliaIsMyCity** [comment]
sounds like a similar issue as chakram
