### ISSUE TITLE
Round 1/2 never started

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#765]
![image](https://user-images.githubusercontent.com/63279022/105622005-92a41e80-5e61-11eb-9459-8d539236fcae.png)
![image](https://user-images.githubusercontent.com/63279022/105622016-9fc10d80-5e61-11eb-9768-b9f9a24dfe74.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ZeSEt6QI) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/105624839-d6eee900-5e78-11eb-946b-1cc134a8cda4.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/105626855-a9a73880-5e82-11eb-9156-16dbedc4469c.png)
Possible cause, can't reliably reproduce it
Sometimes, the starter unit does not disappear, and when the round starts, it gets this error and halts the entire game
![image](https://user-images.githubusercontent.com/19840964/105626876-e2471200-5e82-11eb-8be3-8fe60d3e90ca.png)

**Comment by Snoresville** [comment]
![Image of Yaktocat](https://user-images.githubusercontent.com/19840964/105626855-a9a73880-5e82-11eb-9156-16dbedc4469c.png)
Possible cause, can't reliably reproduce it
Sometimes, the starter unit does not disappear, and when the round starts, it gets an error and halts the entire game

**Comment by Snoresville** [comment]
My bad, I'm not sure if the starter unit is related to this bug
But it does consistently spawn whenever I activate bots

**Comment by fcalife** [comment]
This is a potential fix to this issue, and maybe others: https://github.com/dota2unofficial/custom_hero_clash/commit/76f218e3f0eab4f2be33e638993fd362eb209253

@Snoresville it stops the starter hero from being counted as a unit in many key points in the game, but I'm not sure if that's enough. Maybe you wanna do your own testing.

If this is uploaded and we stop receiving reports of this bug for a week or so, then I think it's safe to say it worked.

**Comment by Snoresville** [comment]
👌

**Comment by Draze22** [comment]
should be fixed.
