### ISSUE TITLE
Devastator doesn't work with tricks of the trade

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#766]
![image](https://user-images.githubusercontent.com/63279022/105651764-d2274500-5f0b-11eb-80ba-cd7cdd0aae84.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/4xUfBWSy) by [Unito](https://www.unito.io/learn-more)

**Comment by darklordabc** [comment]
Testing to see if it synchs with trello

**Comment by Draze22** [comment]
During my testing devastator worked during tricks of the trade.
