### ISSUE TITLE
Betting UI broke and player duelled no one

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#767]
![image](https://user-images.githubusercontent.com/63279022/105666566-a6b55200-5f2d-11eb-8f4d-f43822f8f827.png)
![image](https://user-images.githubusercontent.com/63279022/105666596-bb91e580-5f2d-11eb-9f97-3ad482584945.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/rrY9z5LG) by [Unito](https://www.unito.io/learn-more)

**Comment by Sheodar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix starter hero config (it will fix bugs with UI)](https://trello.com/c/nT6Puzeo/225-fix-starter-hero-config-it-will-fix-bugs-with-ui)

**Comment by Sheodar** [comment]
Fixed
