### ISSUE TITLE
Burning army doesn't work

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#769]
![image](https://user-images.githubusercontent.com/63279022/105789826-395dfb80-5fd7-11eb-87df-3647f439670c.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/tjcp6Gpo) by [Unito](https://www.unito.io/learn-more)

**Comment by Draze22** [comment]
Burning army works fully but we need to add a tooltip explaining which ability it's tied to.

**Comment by darklordabc** [comment]
We are readding death pact very soon, Shush is working on it, its meant to come from that ability yeah?

**Comment by Draze22** [comment]
Makes the most sense to have it tied to searing arrows frosthaven since it works with it but it's currently tied to strafe.

**Comment by Shushishtok** [comment]
It should be tied to Death Pact since it is its Aghs ability.

Death Pact is already done and waiting for a review to be merged.

**Comment by Draze22** [comment]
Burning army isn't linked to death pact in any logical way, it's description literally mention searing arrows on the other hand.
![image](https://user-images.githubusercontent.com/63279022/106440657-31b5bf80-64cd-11eb-8b6c-da7d6578c9be.png)

**Comment by Shushishtok** [comment]
Sure, but then it leaves Death Pact with no aghs effect, unless we make something custom for it.
In Ability Draft, you get Burning Army on Death Pact and not Searing Arrows.

It's just a question of whether we're sticking to vanilla behavior or doing what we want.

**Comment by Draze22** [comment]
Closing this since burning army does work, someone can open a new issue if they wish to discuss what ability burning army should be tied to.
