### ISSUE TITLE
make the shop auto-close when you shift-buy a tome of retraining or paragon

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#770]
So that you can immediately use their interface. QOL improvement. Should only apply to auto-consume (shift-click), and not regular purchase, and only for those 2 items.

┆Issue is synchronized with this [Trello card](https://trello.com/c/ZGAqRY9I) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Apparently some people don't like this idea, I can't really see any problem with it, anyone help me see the light?
![image](https://user-images.githubusercontent.com/7921728/105806933-acd61d80-5f83-11eb-805f-ba1b6253c160.png)

**Comment by fcalife** [comment]
better idea by australia: make this optional (add it to options menu, defaulted to 'yes')

**Comment by ZLOY5** [comment]
I can`t find good ways to implement this.
Maybe it can be done with simple closing shop when this items used?

**Comment by fcalife** [comment]
What's the problem, finding an event to fire? I thought it'd be fine since the ability choosing interface already appears/hides based on shop being open/closed, maybe it's not as easy as it looks

**Comment by ZLOY5** [comment]
There no events clientside for item purchase.
Server side never know if shift is pressed. 
And even if i can fire purchase event from server to client, player can release shift button due to time when data travels between server and client

**Comment by fcalife** [comment]
Could you use this event that launches when the item is auto-consumed? https://github.com/dota2unofficial/custom_hero_clash/blob/8b694858b126e227b97f7278414debb81da9b493/game/scripts/vscripts/game/filters/item.lua#L56

**Comment by fcalife** [comment]
To be clearer, if the event arrives and the player has released shift, then the book does not get auto-consumed. So you don't need to compensate for that
