### ISSUE TITLE
left side hero doesn't show on bet/duel logs

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#772]
![dota2!UNITO-UNDERSCORE!kvCREJLrP5](https://user-images.githubusercontent.com/7921728/105811830-f88cc500-5f8b-11eb-8954-c6ec924291c1.png)

![dota2!UNITO-UNDERSCORE!wJOkEfeeyJ](https://user-images.githubusercontent.com/7921728/105811835-fa568880-5f8b-11eb-9f74-aac553358884.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/xInY2WM7) by [Unito](https://www.unito.io/learn-more)

**Comment by ZLOY5** [comment]
That issue resulted of some bug in encrypter script, so real style overridden by fake

**Comment by ZLOY5** [comment]
I think i find issue reasons
XML contain panel with id #FirstTeamHeroesWrap, that not mentioned in original css by self.
But there also #FirstTeamHeroes panel, that id(and all other) used to create fake selectors in fuzzed css files by adding postfixes
So in fuzzed css files can exist fake styles with #FirstTeamHeroesWrap selector
Solution is fix encrypter in that way to dont use real panels ids and class names
Or never use naming schema like: panel & panel+[postfix](https://github.com/dota2unofficial/custom_game_encrypter/blob/5b645cab50f0f219def574b7de57fc2da8b8ce9d/css-fuzzer.js#L109-L129)

**Comment by fcalife** [comment]
@ZLOY5 nice detective work, thanks!
