### ISSUE TITLE
Lobbies started with less than full players are still scored

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#773]
![image](https://user-images.githubusercontent.com/63279022/105825225-7942d400-6013-11eb-813b-b148521d3086.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/TDGp3kc6) by [Unito](https://www.unito.io/learn-more)

**Comment by SanctusAnimus** [comment]
@fcalife by the way, this should be checked on lua side, cause we send after-match on per-team basis, so there is no way for the server to know wether game is eligible or not

**Comment by fcalife** [comment]
Should be fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/c8d7912a392a8894cf8822f970585383e0c9dd01
