### ISSUE TITLE
Make a new free tresure that refreshes every day

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#775]
The idea applies to Overthrow and 12v12 too.

┆Issue is synchronized with this [Trello card](https://trello.com/c/fFLeCcjG) by [Unito](https://www.unito.io/learn-more)

**Comment by fcalife** [comment]
Duplicate of https://github.com/dota2unofficial/custom_hero_clash_issues/issues/776
