### ISSUE TITLE
Creep pathing is super weird

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#800]
The creeps seem to walk around invisible objects to get to players, they sometimes try to attack dead units and generally look super weird when they walk around a lot of the time.

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106287308-c389b680-629a-11eb-93d3-b7eb5c27fdf5.png)

**Comment by fcalife** [comment]
Fixed in https://github.com/dota2unofficial/custom_hero_clash/commit/ee11c6f3c716817c5169150153ab41915971a602
