### ISSUE TITLE
Cooldowns overlay resets visually while in the fountain instead of beeing reduced

### ISSUE THREAD

**Issue by Nibuja05** [dota2unofficial/custom_hero_clash_issues#802]
While in fountain the cooldowns get reduced by 1 second, which causes the cooldown overlay to keep resetting.
There is already a library to handle this kind of issue: https://github.com/Nibuja05/Dota-Better-Cooldowns

**Comment by Nibuja05** [comment]
Is already part of the following issue: https://github.com/dota2unofficial/custom_hero_clash_issues/issues/803

**Comment by Nibuja05** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Better Cooldowns (part of UI Improvement Suggestions by Shush)](https://trello.com/c/R6byNSTa/228-implement-better-cooldowns-part-of-ui-improvement-suggestions-by-shush)

**Comment by Draze22** [comment]
This was fixed in this pull request https://github.com/dota2unofficial/custom_hero_clash/pull/716.
