### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by Shushishtok** [dota2unofficial/custom_hero_clash_issues#803]
I've played a couple games and looked around the UI, which is beautiful and well done. Here are some suggestions that should be simple to implement and would most likely improve it. Slightly. Here we go!

- When hovering on the Voice Wheel toggle button, you can see the following text (in English):
"You can open Voice Wheel (Press L)".
![Voice Wheel](https://cdn.discordapp.com/attachments/682631693172998165/804818140269510666/unknown.png)
The text should be improved to something much shorter and to the point. Suggested text: "Open voice wheel (L)".

- When hovering on the question mark icon when the next group of enemies have no abilities, the icon does nothing, though it still changes to red when hovered on and back to gray when hovering out.
![Question mark](https://cdn.discordapp.com/attachments/682631693172998165/804818566624444466/unknown.png)
Suggestion: Remove the "?" icon when it has nothing to show.

- Between rounds, your abilities' and items' cooldown decrease by 1 every second if they're on cooldown, which causes the UI of the ability/item to reset its overlay. I recommend using Nibuja's [Better Cooldowns](https://github.com/Nibuja05/Dota-Better-Cooldowns) library, which is very simple and easy to implement, which overrides the functions and shows relative cooldown overlay. [Here](https://streamable.com/0umzbw) is an ability in my own mode that utilizes this: it shows how it looks before and after implementing the Better Cooldown library.

- Ogre Seals' Ogre Seal Flop doesn't have any texture on the ability, and is a blank square.
![Ogre Seal Flop](https://cdn.discordapp.com/attachments/682631693172998165/804819929102680095/unknown.png)
Suggestion: Give it a proper texture.

- Mastery, History, Options panels could have their behaviors tweaked to match the shop behavior.
  - Pressing ESC closes the panel.
  - Clicking outside of their area (focus loss) closes the panel.
  - Add hotkeys for toggling the panels on and off. Those hotkeys can use base game hotkeys that are not used, such as the Activate Glyph hotkey.

**Comment by Shushishtok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI Improvement Suggestions by Shush](https://trello.com/c/38OgH14J/219-ui-improvement-suggestions-by-shush)

**Comment by darklordabc** [comment]
> The text should be improved to something much shorter and to the point. Suggested text: "Open voice wheel (L)".

I agree

> Suggestion: Remove the "?" icon when it has nothing to show.

Agreed

> Between rounds, your abilities' and items' cooldown decrease by 1 every second if they're on cooldown, which causes the UI of the ability/item to reset its overlay. I recommend using Nibuja's Better Cooldowns library, which is very simple and easy to implement, which overrides the functions and shows relative cooldown overlay. Here is an ability in my own mode that utilizes this: it shows how it looks before and after implementing the Better Cooldown library.

I agree with the caveat that this actually works as intended and is not a huge pain to implment. 

> Ogre Seals' Ogre Seal Flop doesn't have any texture on the ability, and is a blank square.

Sure, we should fix this.

> Pressing ESC closes the panel.
> Clicking outside of their area (focus loss) closes the panel.
> Add hotkeys for toggling the panels on and off. Those hotkeys can use base game hotkeys that are not used, such as the Activate Glyph hotkey.

I agree with all of this, nice suggestions.

**Comment by Shushishtok** [comment]
> I agree with the caveat that this actually works as intended and is not a huge pain to implment.

Works for me, the attached video shows that ;p

**Comment by ZLOY5** [comment]
Remains only Ogre Seal Flop texture

**Comment by Shushishtok** [comment]
I can take care of that.

**Comment by Shushishtok** [comment]
Need to wait for all three issues to be merged:
UI improvements dota2unofficial/custom_hero_clash#710 - merged
Implementation of Better Cooldowns dota2unofficial/custom_hero_clash#716 - post-review changes
Added custom texture icon for Ogreseal Flop dota2unofficial/custom_hero_clash#718 - waiting for review
