### ISSUE TITLE
Rework betting reward algorithm to be less rewarding to 1 gold underdog bets

### ISSUE THREAD

**Issue by fcalife** [dota2unofficial/custom_hero_clash_issues#812]
This has been overdue for some time. The objective is not to make small underdog bets are a *bad* idea, but just to make the split fairer between the better and the duelist.

There's been a lot of discussion on this, @AustraliaIsMyCity is privy to it. My opinion is that the simplest and most effective way to implement this without changing the game's economy too much is to make it so the duelist earns a part of the bet winnings when only a few people bet on them (1-2 at most). This would be in addition to their usual 40% cut.

It would look something like this:
 - If only 1 player bet on the winner: bet winner and duelist split the prize money as if the duelist had placed a bet on themselves equal to 10% of all bets.
 - If only 2 player bet on the winner: bet winners and duelist split the prize money as if the duelist had placed a bet on themselves equal to 5% of all bets.
 - If 3 or more players bet on the winner: same as the current mechanics.

The actual numbers for this change can be tweaked/discussed by anyone willing to go into the math of it.

**Comment by AustraliaIsMyCity** [comment]
sounds like its time for a sin wave

**Comment by AustraliaIsMyCity** [comment]
Old system:
Duel winner gets 100% of the pot if no one bets on them or 40% if anyone does
Betters get 100% of the pot * their bet / total amount bet on the winner

New system:
Duel winner gets total_pot * max(0.5, 1 - pct_bet_on_winner * 2.5))
Betters get total_pot * min(1, pct_bet_on_winner * 3.75) * their bet / total amount bet on the winner

**Comment by AustraliaIsMyCity** [comment]
it should be noted that is only a fix for underbetting, overbetting is still an issue which ill come up with a solution for in a few days

**Comment by AustraliaIsMyCity** [comment]
Fixed overbetting too:

Old system:
Duel winner gets 100% of the pot if no one bets on them or 40% if anyone does
Betters get 100% of the pot * their bet / total amount bet on the winner

New system:
Duel winner gets `min(total_pot * max(0.5, 1 - pct_bet_on_winner * 2.5)), 2.5 * base_pot + total_bet_on_loser)`
Betters get `total_pot * min(1, pct_bet_on_winner * 3.75) * their bet / total_bet_on_winner`

**Comment by AustraliaIsMyCity** [comment]
done https://github.com/dota2unofficial/custom_hero_clash/pull/698
