### ISSUE TITLE
Cant unlearn Phoenix - Fire Spirits if you have Aghanim's shard

### ISSUE THREAD

**Issue by Cronusa** [dota2unofficial/custom_hero_clash_issues#815]
Hi, if you have Aghanim's Shard and discard ability into Fire Spirits, it becomes passive and you can not unlearn it.
Either disable aghanim's shard benefits on that spell, or make it impossible to get from Discarding. 
It ruined 3 games  already for me. Please fix <3

**Comment by Cronusa** [comment]
> we already know about this.

This has been issue for more than a week now.

**Comment by Snoresville** [comment]
the next update has the fix
