### ISSUE TITLE
Marksmanship rework changed the functionality slightly

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#819]
![image](https://user-images.githubusercontent.com/63279022/106376347-a95dee80-63e8-11eb-9db9-381358de4d8b.png)

**Comment by Snoresville** [comment]
![image](https://user-images.githubusercontent.com/19840964/106376366-9ba66a00-63e4-11eb-8a45-e5d28e6a78f6.png)
yup, splinter was changed to hit the closest targets

**Comment by Shushishtok** [comment]
@Draze22 Is this a bug? Can be very easily fixed by changing `FIND_CLOSEST` to `FIND_ANY`.

**Comment by Draze22** [comment]
Yes, it should be random.

**Comment by Draze22** [comment]
Fixed.
