### ISSUE TITLE
Metamorphosis sometimes doesn't give terror wave

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#827]
![image](https://user-images.githubusercontent.com/63279022/106452009-69c3ff00-64db-11eb-9889-a7fe977b9c2f.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106453225-12bf2980-64dd-11eb-8ce0-dac4199b5a59.png)

**Comment by Shushishtok** [comment]
Does it work "sometimes" like the title says, or just never?
Is this the new Metamophorsis done by @Snoresville ?
It may simply lack the appropriate AD link field.

**Comment by Draze22** [comment]
Didn't work for me but people have reported it disappearing on them so it seems it does work sometimes.

**Comment by Snoresville** [comment]
yes, forgot to add the ability to metamorphosis upgrade
