### ISSUE TITLE
Demonic purge doesn't work properly

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#828]
![image](https://user-images.githubusercontent.com/63279022/106452101-89f3be00-64db-11eb-9686-54644b0f02ee.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/106453355-48641280-64dd-11eb-83c3-b95e297fe620.png)

**Comment by darklordabc** [comment]
I dont understand, is it working or not? It looks like its working?

**Comment by Draze22** [comment]
It's not working properly, it lasts for 3000 seconds and doesn't seem to slow or break.

**Comment by fcalife** [comment]
https://github.com/dota2unofficial/custom_hero_clash/commit/a201e6dfcfd4864c7017eb49a4d4826834852250 fixes Demonic Purge straight up crashing the game on use, but it still has several issues:

 - Buying scepter doesn't grant additional charges immediately;
 - Cannot be targeted on allies with shard;
 - Does not play any sound on cast;
 - Does not deal any damage after the duration expires (I assume the allied version also applies no healing, though that's impossible to test currently);
