### ISSUE TITLE
Issue with glory, fortune and cosmetics getting removed

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#840]
![image](https://user-images.githubusercontent.com/63279022/107001059-1274a600-67dd-11eb-8e25-985b183b712d.png)

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue with glory, fortune and cosmetics getting removed #840](https://trello.com/c/v865TN3s/280-issue-with-glory-fortune-and-cosmetics-getting-removed-840)

**Comment by Sheodar** [comment]
Should be fixed
