### ISSUE TITLE
Quest window opens automatically

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#854]
![image](https://user-images.githubusercontent.com/63279022/107178385-27914500-6a28-11eb-9e05-5368ab3229a4.png)
![image](https://user-images.githubusercontent.com/63279022/107178392-2bbd6280-6a28-11eb-9615-d58b58c4ea2f.png)

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quest window opens automatically #854](https://trello.com/c/mCab4Aoh/279-quest-window-opens-automatically-854)

**Comment by Sheodar** [comment]
It's part of logic for tracker. It will open every 5min if player didn't open this last 5mins

**Comment by Sheodar** [comment]
Updated logic. Removed auto-opening by timer
