### ISSUE TITLE
Quest UI blocks the ping and fps info

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#857]
Just needs to be moved down a bit.

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quest UI blocks the ping and fps info](https://trello.com/c/j7P8i6Pt/278-quest-ui-blocks-the-ping-and-fps-info)

**Comment by Sheodar** [comment]
Added button for shrink this
