### ISSUE TITLE
Hoodwink can't consume Aghanim's Scepter

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#858]
![image](https://user-images.githubusercontent.com/63279022/107183927-c0798d80-6a33-11eb-9c01-c1ee993ff80f.png)

**Comment by Snoresville** [comment]
who tf said hoodwink can do that now

**Comment by Draze22** [comment]
Buying the Aghanim's Blessing recipe tries to consume the Aghanim's Scepter which doesn't work and you end up simply losing 1600 gold from buying the recipe.

**Comment by Snoresville** [comment]
that's an oof

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hoodwink can't consume Aghanim's Scepter #858](https://trello.com/c/NwKJFdUH/281-hoodwink-cant-consume-aghanims-scepter-858)
