### ISSUE TITLE
Ghost Walk doesn't scale logically

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#860]
![image](https://user-images.githubusercontent.com/63279022/107187189-ba86ab00-6a39-11eb-9721-1e0df93ef3b4.png)

**Comment by lovro-m** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ghost Walk doesn't scale logically](https://trello.com/c/2INSfSdG/283-ghost-walk-doesnt-scale-logically)

**Comment by lovro-m** [comment]
Balance team, should this be changed from -10 5 20 35 to 0 10 20 35% to avoid having negative and positive numbers?

**Comment by Draze22** [comment]
Make it 5/15/25/35%.
