### ISSUE TITLE
Buying Aghanim's Blessing on Hoodwink stops you from getting Aghanim's effects

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#861]
![image](https://user-images.githubusercontent.com/63279022/107187390-08031800-6a3a-11eb-8c3b-dc9179abcb35.png)

**Comment by Draze22** [comment]
Selling your Aghanim's Scepter and buying a new one fixes this bug.

![image](https://user-images.githubusercontent.com/63279022/107187434-1a7d5180-6a3a-11eb-8a66-0b8889c77155.png)

**Comment by Draze22** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Buying Aghanim's Blessing on Hoodwink stops you from getting Aghanim's effects #861](https://trello.com/c/xqLto2JS/282-buying-aghanims-blessing-on-hoodwink-stops-you-from-getting-aghanims-effects-861)

**Comment by darklordabc** [comment]
Ban this hero from buying blessing. And give an item that explains that she can't buy blessing and on consume gives like 200 gold.
