### ISSUE TITLE
Asian lobbies(?) takes too long to find a server

### ISSUE THREAD

**Issue by Roshrach** [dota2unofficial/custom_hero_clash_issues#864]
I don't know if this is valve's fault or the game's fault but I've been trying to play the game for an hour now and finding a server takes a lot of time and makes other players quit due to lack of patience. the longest finding time that i had is 6 minutes. I have joined atleast 7 lobbies and none of them are successful since it takes too long to find a server. This happened since the update was released. (I'm writing this while finding a game by the way.)
![image](https://user-images.githubusercontent.com/78736351/107220915-e57afa00-6a4d-11eb-8dc8-ce1e9cba8f37.png)

**Comment by Snoresville** [comment]
Someone mentioned that this could be due to steam China releasing tomorrow

**Comment by Draze22** [comment]
There's nothing we can do about this.
