### ISSUE TITLE
Nature's Prophet's 2.6x treant hp/damage talent doesn't increase health

### ISSUE THREAD

**Issue by Draze22** [dota2unofficial/custom_hero_clash_issues#865]
![image](https://user-images.githubusercontent.com/63279022/107224475-9479fe80-6a6b-11eb-8147-0a0e8ada977c.png)

**Comment by Nibuja05** [comment]
Same problem as https://github.com/dota2unofficial/custom_hero_clash_issues/issues/746
I have discovered the issue and am fixing it.

**Comment by Nibuja05** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Nature's Prophet's treant hp/damage talent doesn't increase health #865](https://trello.com/c/9vAyG848/285-natures-prophets-treant-hp-damage-talent-doesnt-increase-health-865)
