### ISSUE TITLE
Neutral items can be sold by eliminated players allowing them to get money after being eliminated

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#88]
leads to issues where players can drop stat tomes to influence the state of the game after death

**Comment by Draze22** [comment]
Can confirm this can still be done

**Comment by Draze22** [comment]
Players who happen to have bought a large number of books before dying can also drop them to other players and if a player dies and then gets money from a bet they can spend that money on attribute books and drop them for other players.

**Comment by darklordabc** [comment]
We can fix this by disabling orders from dead players.

**Comment by SanctusAnimus** [comment]
Dead players will no longer be able to issue orders (completely dead, not reincarnating)
