### ISSUE TITLE
Why is "Hero Skins" showing in cosmetic window but its empty? 

### ISSUE THREAD

**Issue by darklordabc** [dota2unofficial/custom_hero_clash_issues#901]
![image](https://user-images.githubusercontent.com/16277198/108208118-ba468800-717c-11eb-8860-935eefcced78.png)

**Comment by SanctusAnimus** [comment]
Technically it has one skin for tournament milestone (i don't rember for which place it was given), and thus it's only showing when you have it, i think

**Comment by fcalife** [comment]
It should simply not show if you do not have any cosmetics in that category. That logic is already in place for other categories which are currently invisible.

This is probably due to the category being new and not being covered by said logic. @Sheodar can you check?

**Comment by Sheodar** [comment]
Fixed
