### ISSUE TITLE
"Allow certain abilities that don't normally target creeps to do so" MegaThread

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [dota2unofficial/custom_hero_clash_issues#93]
Burning army [Clinkz]
Dream coil [Puck]
Heat seeking missile [Tinker]
Reflection [Terrorblade] (creep illusions sounds strange)
Static link [Razor]
Unstable concoction [Alchemist]
Ice blast [Ancient Apparition] (DoT and kill threshold)
Souldbind [Grimstroke]
Omnislash [Juggernaut] (allow use on Rosh?)
Skewer [Magnus]
Spear of mars [Mars]
Sanity's eclipse [Outworld Devourer]
Disruption [Shadow Demon] (see Reflection)
Sunder [Terrorblade] 
Maledict [Witch Doctor]

**Comment by Draze22** [comment]
Reflection sounds super hard to code and will add extra server lag so maybe leave that one out.

**Comment by Draze22** [comment]
Decay [Undying]

**Comment by li0nza** [comment]
These also don't work against creeps:
Jingu Mastery [Monkey King]
Spiked Carapace [Nyx]

**Comment by AustraliaIsMyCity** [comment]
Pit of malice [Underlord]

**Comment by fcalife** [comment]
Implemented:

- Burning army [Clinkz]
- Dream coil [Puck]
- Heat seeking missile [Tinker]
- Static link [Razor]
- Omnislash [Juggernaut]
- Skewer [Magnus]
- Sunder [Terrorblade]
- Maledict [Witch Doctor]
- Jingu Mastery [Monkey King]
- Decay [Undying]

Implemented, but don't work fully against creeps

- Unstable concoction [Alchemist] - No aoe effect on impact
- Ice blast [Ancient Apparition] - Damage only, no DoT or kill threshold effect
- Soulbind [Grimstroke] - Doesn't link to other creeps
- Disruption [Shadow Demon] - Does not create illusions

Don't really make sense against creeps:

- Reflection [Terrorblade] - creep illusions don't really make sense
- Spear of mars [Mars] - it already works against creeps, just doesn't pin them to walls?

Remaining abilities:

- Sanity's eclipse [Outworld Devourer]
- Spiked Carapace [Nyx]

@darklordabc @Draze22 So, out of those, which ones should be implemented? Only Spiked Carapace and Sanity's Eclipse? Any of those require complete reworks, so try to be picky about them.

**Comment by fcalife** [comment]
Split this issue on each of the skills that are going to be reworked, for easier tracking:

#508 #509 #510 #511 #512 #513 #514 #515
